'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test, tests, childProcess } = require('./_helpers.js');
const runner = require('../scripts/agent-run.js');
const controls = require('../scripts/agent-controls.js');
const ledger = require('../scripts/operator-action-ledger.js');
const cancellationAdapters = require('../scripts/agent-cancellation-adapters.js');

function write(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); }
function fixture(lifecycle = { doctrine: 'DEFINED', proven: 'PROVEN', autonomous_dispatch: 'ENABLED' }) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-controls-'));
  write(path.join(root, 'config/agent-registry.json'), { schema_version: 1, agents: [{ agent_id: 'alpha', name: 'Alpha', lifecycle }] });
  fs.mkdirSync(path.join(root, 'scripts'), { recursive: true });
  fs.writeFileSync(path.join(root, 'scripts/alpha.js'), `'use strict';\nconst fs=require('fs');const AGENT_ID='alpha';const ACTIONS=['work'];if(require.main===module){const p=process.argv[process.argv.indexOf('--task')+1];const t=JSON.parse(fs.readFileSync(p));if(t.hold)setTimeout(()=>{},30000);else console.log(JSON.stringify({agent_id:AGENT_ID,task_id:t.task_id,state:'COMPLETE',attention:'INFORMATION',events:[],visual_plan:{version:t.version||1},control_room:{state:'COMPLETE',attention_level:'INFORMATION'}}));}module.exports={AGENT_ID,ACTIONS};\n`);
  const taskPath = path.join(root, 'task.json');
  write(taskPath, { task_id: 'task-1', package_run_id: 'run-1', assignment: { action: 'work' }, lane: 'local', model: 'model-a' });
  return { root, taskPath, actor: ledger.localActorContext({ username: 'mikko' }) };
}
function digestTree(root) { const hash = crypto.createHash('sha256'); (function walk(dir) { for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const full = path.join(dir, entry.name); if (entry.isDirectory()) walk(full); else hash.update(path.relative(root, full)).update(fs.readFileSync(full)); } })(root); return hash.digest('hex'); }
async function completed(f) { return runner.runRegisteredAgent({ repoRoot: f.root, agentId: 'alpha', runId: 'run-1', taskPath: f.taskPath }); }
function target(out, reason = 'Retry exact failed work.') { return { run_id: 'run-1', agent_id: 'alpha', invocation_id: out.invocation.invocation_id, reason }; }

test('retry preview is read-only and binds exact invocation bytes', async () => { const f = fixture(), first = await completed(f); const before = digestTree(f.root), preview = controls.previewRetry(target(first), { root: f.root }); assert.equal(preview.eligible, true); assert.equal(preview.creates_new_attempt, true); assert.equal(preview.changes_approval, false); assert.equal(digestTree(f.root), before); });
test('retry apply creates a new attempt, ledger record, and preserves old evidence', async () => { const f = fixture(), first = await completed(f); const old = path.join(f.root, 'package-runs/run-1/agents/alpha/task-1/invocation.json'); const oldBytes = fs.readFileSync(old); const approval = path.join(f.root, 'package-runs/run-1/manual-approval.json'); write(approval, { scope: 'FINAL_CUT_APPROVAL', marker: 'unchanged' }); const approvalBytes = fs.readFileSync(approval); const p = controls.previewRetry(target(first), { root: f.root }); const result = await controls.applyRetry({ ...target(first), preview_token: p.preview_token }, { root: f.root, actor: f.actor, recordId: 'operator-action-retry-1', now: '2026-08-24T08:00:00.000Z' }); assert.equal(result.new_invocation_id, 'alpha:task-1:2'); assert.deepEqual(fs.readFileSync(old), oldBytes); assert.deepEqual(fs.readFileSync(approval), approvalBytes); const records = ledger.readLedger(f.root, 'run-1').records; assert.equal(records.length, 1); assert.equal(records[0].action, 'RETRY'); assert.equal(JSON.stringify(records[0]).includes('approval'), false); });
test('retry requires a current preview and cannot target a disabled role', async () => { const f = fixture(), first = await completed(f); await assert.rejects(() => controls.applyRetry({ ...target(first), preview_token: '0'.repeat(64) }, { root: f.root, actor: f.actor }), (e) => e.code === 'AGENT_CONTROL_PREVIEW_STALE'); const disabled = fixture({ doctrine: 'DEFINED', proven: 'NOT_PROVEN', autonomous_dispatch: 'DISABLED' }); assert.throws(() => controls.previewRetry({ run_id: 'run-1', agent_id: 'alpha', invocation_id: 'alpha:task-1:1', reason: 'No bypass.' }, { root: disabled.root }), (e) => e.code === 'BLOCKED_AGENT_NOT_ENABLED'); });
test('cancel without an exact bound provider records NOT_SUPPORTED and does not claim remote stop', async () => { const f = fixture(); write(f.taskPath, { task_id: 'task-1', package_run_id: 'run-1', assignment: { action: 'work' }, hold: true }); const wrapper = path.join(f.root, 'runner.js'); fs.writeFileSync(wrapper, `require(${JSON.stringify(path.join(__dirname, '../scripts/agent-run.js'))}).runRegisteredAgent({repoRoot:${JSON.stringify(f.root)},agentId:'alpha',runId:'run-1',taskPath:${JSON.stringify(f.taskPath)}});\n`); const child = childProcess.spawn(process.execPath, [wrapper], { stdio: 'ignore' }); const lockPath = path.join(f.root, 'package-runs/run-1/agents/.lock'); let lock; for (let i = 0; i < 100; i++) { if (fs.existsSync(lockPath)) { lock = JSON.parse(fs.readFileSync(lockPath)); if (lock.invocation_id) break; } await new Promise((resolve) => setTimeout(resolve, 10)); } try { const input = { run_id: 'run-1', agent_id: 'alpha', invocation_id: lock.invocation_id, reason: 'Stop only if a real provider is bound.' }; const p = controls.previewCancel(input, { root: f.root }); assert.equal(p.eligible, false); assert.equal(p.remote_may_continue, true); const result = await controls.applyCancel({ ...input, preview_token: p.preview_token }, { root: f.root, actor: f.actor, recordId: 'operator-action-cancel-1' }); assert.equal(result.result_status, 'NOT_SUPPORTED'); assert.equal(result.remote_may_continue, true); assert.equal(ledger.readLedger(f.root, 'run-1').records[0].result_status, 'NOT_SUPPORTED'); } finally { child.kill('SIGKILL'); await new Promise((resolve) => child.once('exit', resolve)); } });
test('exact worker cancellation records provider outcome without changing approval or evidence', async () => { const f = fixture(); write(f.taskPath, { task_id: 'task-1', package_run_id: 'run-1', assignment: { action: 'work' }, hold: true }); const wrapper = path.join(f.root, 'runner.js'); fs.writeFileSync(wrapper, `require(${JSON.stringify(path.join(__dirname, '../scripts/agent-run.js'))}).runRegisteredAgent({repoRoot:${JSON.stringify(f.root)},agentId:'alpha',runId:'run-1',taskPath:${JSON.stringify(f.taskPath)}});\n`); const child = childProcess.spawn(process.execPath, [wrapper], { stdio: 'ignore' }); const lockPath = path.join(f.root, 'package-runs/run-1/agents/.lock'); let lock; for (let i = 0; i < 100; i++) { if (fs.existsSync(lockPath)) { lock = JSON.parse(fs.readFileSync(lockPath)); if (lock.invocation_id) break; } await new Promise((resolve) => setTimeout(resolve, 10)); } try { const persistedTask = path.join(f.root, 'package-runs/run-1/agents', lock.task_directory, 'task.json'); cancellationAdapters.writeBinding(persistedTask, { provider_id: 'flux', job_id: 'job-1', host: 'vidnux' }, { invocationId: lock.invocation_id, taskSha256: runner.sha256(fs.readFileSync(persistedTask)), bindingPath: path.join(path.dirname(persistedTask), 'resource-job.json') }); const approval = path.join(f.root, 'package-runs/run-1/manual-approval.json'); write(approval, { scope: 'FINAL_CUT_APPROVAL', marker: 'unchanged' }); const approvalBytes = fs.readFileSync(approval), evidenceBytes = fs.readFileSync(persistedTask); const provider = cancellationAdapters.createProvider({ flux: { host: 'vidnux', status: async () => ({ active: true, job_id: 'job-1' }), cancel: async () => ({ ok: true, signal_sent: 'SIGTERM' }), remoteMayContinue: true } }); const input = { run_id: 'run-1', agent_id: 'alpha', invocation_id: lock.invocation_id, reason: 'Stop the exact bound worker job.' }; const p = controls.previewCancel(input, { root: f.root, cancelProvider: provider }); assert.equal(p.eligible, true); const out = await controls.applyCancel({ ...input, preview_token: p.preview_token }, { root: f.root, actor: f.actor, cancelProvider: provider, recordId: 'operator-action-cancel-bound-1' }); assert.equal(out.outcome, 'REMOTE_MAY_CONTINUE'); assert.deepEqual(fs.readFileSync(approval), approvalBytes); assert.deepEqual(fs.readFileSync(persistedTask), evidenceBytes); const record = ledger.readLedger(f.root, 'run-1').records[0]; assert.equal(record.result_details.job_id, 'job-1'); assert.equal(record.result_details.remote_may_continue, true); } finally { child.kill('SIGKILL'); await new Promise((resolve) => child.once('exit', resolve)); } });
test('takeover preview is read-only and apply fences runner, retry, and direct executable boundary', async () => { const f = fixture(), first = await completed(f); const input = { ...target(first, 'Take bounded ownership.'), }; const before = digestTree(f.root); const preview = controls.previewTakeManualControl(input, { root: f.root }); assert.equal(preview.eligible, true); assert.equal(digestTree(f.root), before); const retryPreview = controls.previewRetry(target(first), { root: f.root }); const taken = controls.applyTakeManualControl({ ...input, preview_token: preview.preview_token }, { root: f.root, actor: f.actor, recordId: 'operator-action-take-1' }); assert.equal(taken.execution_owner, 'HUMAN'); await assert.rejects(() => runner.runRegisteredAgent({ repoRoot: f.root, agentId: 'alpha', runId: 'run-1', taskPath: f.taskPath, newAttempt: true }), (e) => e.code === 'AUTOMATION_FENCED'); assert.throws(() => controls.previewRetry(target(first), { root: f.root }), (e) => e.code === 'AUTOMATION_FENCED'); await assert.rejects(() => controls.applyRetry({ ...target(first), preview_token: retryPreview.preview_token }, { root: f.root, actor: f.actor }), (e) => e.code === 'AUTOMATION_FENCED'); const boundary = require('../scripts/agent-executable-boundary.js'); let stdout = ''; assert.equal(boundary.guardExecutableLifecycle('alpha', { repoRoot: f.root, argv: ['--task', f.taskPath], stdout: { write: (s) => { stdout += s; } }, setExitCode: false }), false); assert.match(stdout, /AUTOMATION_FENCED/); });
test('return allows unchanged bytes but changed manual bytes remain fenced without a successor-task contract', async () => { const unchanged = fixture(), first = await completed(unchanged); const input = target(first, 'Inspect without changing bytes.'); let p = controls.previewTakeManualControl(input, { root: unchanged.root }); controls.applyTakeManualControl({ ...input, preview_token: p.preview_token }, { root: unchanged.root, actor: unchanged.actor, recordId: 'operator-action-take-1' }); const returnInput = target(first, 'Return unchanged bytes.'); const ready = await controls.previewReturnToAutomation(returnInput, { root: unchanged.root }); assert.equal(ready.eligible, true); const returned = await controls.applyReturnToAutomation({ ...returnInput, preview_token: ready.preview_token }, { root: unchanged.root, actor: unchanged.actor, recordId: 'operator-action-return-1' }); assert.equal(returned.execution_owner, 'AUTOMATION'); const changed = fixture(), changedFirst = await completed(changed), changedInput = target(changedFirst, 'Manual artifact correction.'); p = controls.previewTakeManualControl(changedInput, { root: changed.root }); controls.applyTakeManualControl({ ...changedInput, preview_token: p.preview_token }, { root: changed.root, actor: changed.actor, recordId: 'operator-action-take-2' }); fs.writeFileSync(path.join(changed.root, 'package-runs/run-1/agents/alpha/task-1/artifacts/visual-plan.json'), '{"version":2}\n'); const blocked = await controls.previewReturnToAutomation(target(changedFirst, 'Attempt return after mutation.'), { root: changed.root, revalidate: async () => ({ valid: true }) }); assert.equal(blocked.eligible, false); assert.equal(blocked.invalidations.prior_evidence, 'STALE'); assert.match(blocked.revalidation.reason, /successor-task contract/); });
test('takeover refuses any active runner lock and disabled lifecycle remains authoritative', async () => { const f = fixture(), first = await completed(f); const agents = path.join(f.root, 'package-runs/run-1/agents'); write(path.join(agents, '.lock'), { pid: process.pid, host: os.hostname(), acquired_at: new Date().toISOString(), token: 'x' }); assert.equal(controls.previewTakeManualControl(target(first, 'Do not race active automation.'), { root: f.root }).eligible, false); fs.unlinkSync(path.join(agents, '.lock')); const disabled = fixture({ doctrine: 'DEFINED', proven: 'NOT_PROVEN', autonomous_dispatch: 'DISABLED' }); assert.throws(() => controls.previewTakeManualControl({ run_id: 'run-1', agent_id: 'alpha', invocation_id: 'alpha:task-1:1', reason: 'No lifecycle bypass.' }, { root: disabled.root }), (e) => e.code === 'BLOCKED_AGENT_NOT_ENABLED'); });
test('canonical runner and executable boundary fail closed after ownership state deletion', async () => { const f = fixture(), first = await completed(f); const input = target(first, 'Take ownership before deletion regression.'); const preview = controls.previewTakeManualControl(input, { root: f.root }); controls.applyTakeManualControl({ ...input, preview_token: preview.preview_token }, { root: f.root, actor: f.actor, recordId: 'operator-action-delete-regression' }); const ownershipModule = require('../scripts/execution-ownership.js'); fs.unlinkSync(ownershipModule.pathsFor(f.root, { run_id: 'run-1', agent_id: 'alpha', task_id: 'task-1' }).statePath); await assert.rejects(() => runner.runRegisteredAgent({ repoRoot: f.root, agentId: 'alpha', runId: 'run-1', taskPath: f.taskPath, newAttempt: true }), (e) => e.code === 'OWNERSHIP_REQUIRED_MISSING'); const boundary = require('../scripts/agent-executable-boundary.js'); let stdout = ''; assert.equal(boundary.guardExecutableLifecycle('alpha', { repoRoot: f.root, argv: ['--task', f.taskPath], stdout: { write: (s) => { stdout += s; } }, setExitCode: false }), false); assert.match(stdout, /OWNERSHIP_REQUIRED_MISSING/); });

if (require.main === module) { (async () => { let passed = 0; for (const item of tests) { try { await item.fn(); passed++; console.log(`ok - ${item.name}`); } catch (error) { console.error(`not ok - ${item.name}`); console.error(error); process.exitCode = 1; break; } } console.log(`${passed}/${tests.length} Agent Control tests passed`); })(); }
