'use strict';

const { assert, fs, os, path, test } = require('./_helpers.js');
const storyFixture = require('./story-authority-live-fixture.js');
const storyBinding = require('../scripts/package-run-story-binding.js');
const mode = require('../scripts/package-run-production-mode.js');
const planning = require('../scripts/agent-task-visual-planning.js');
const director = require('../scripts/visual-planning-director.js');
const vp = require('../scripts/visual-plan.js');
const bespoke = require('../scripts/draft-bespoke-still-policy.js');
const successor = require('../scripts/draft-bespoke-successor-authority.js');
const renderer = require('../scripts/production-assembly-renderer.js');
const composition = require('../scripts/production-assembly-composition.js');
const handoff = require('../scripts/directed-draft-assembly-handoff.js');

function writeJson(file, value) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); return file; }
function H(value) { return require('node:crypto').createHash('sha256').update(value).digest('hex'); }
function storyVersionFile(story, version) { return path.join(story.dataRoot, 'projects', story.project.id, 'versions', `${version.id}.md`); }
function errorCode(fn, code) { assert.throws(fn, (error) => error.code === code, code); }
async function rejectCode(fn, code) { await assert.rejects(fn, (error) => error.code === code, code); }

function approvedStoryEstate(options = {}) {
  const authority = storyFixture.canonicalStoryFixture();
  const project = authority.store.newProject({ id: options.projectId || 'draft-successor-project', title: 'Draft successor fixture', length_class: 'short' });
  project.output_class = { aspect_ratio: '9:16', orientation: 'vertical', length_class: 'short', max_duration_minutes: 3 };
  authority.store.saveProject(authority.dataRoot, project);
  const sectionsV1 = Array.from({ length: 11 }, (_, index) => ({ id: `S${String(index + 1).padStart(2, '0')}`, order: index + 1, beat: `Beat ${index + 1}`, type: 'composited', dialogue: `Original exact script line ${index + 1}.`, visual_notes: '', media_refs: [] }));
  const v1 = authority.versions.createVersion(authority.dataRoot, project, sectionsV1, authority.config.loadConfig(authority.dataRoot), {});
  authority.versions.approveVersion(authority.dataRoot, project, v1.id, { note: 'Human authority: Mikko. Fixture predecessor approval.' }); authority.store.saveProject(authority.dataRoot, project);
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 3);
  const sectionsV2 = sectionsV1.map((section, index) => ({ ...section, dialogue: `Current approved exact script line ${index + 1}.` }));
  const v2 = authority.versions.createVersion(authority.dataRoot, project, sectionsV2, authority.config.loadConfig(authority.dataRoot), {});
  if (options.approveCurrent !== false) { authority.versions.approveVersion(authority.dataRoot, project, v2.id, { note: 'Human authority: Mikko. Fixture current approval.' }); authority.store.saveProject(authority.dataRoot, project); }
  return { ...authority, project, v1, v2, sectionsV1, sectionsV2 };
}

function baseRunEstate(options = {}) {
  const story = approvedStoryEstate(options); const repo = fs.mkdtempSync(path.join(os.tmpdir(), 'draft-successor-repo-'));
  const runs = path.join(repo, 'package-runs'); fs.mkdirSync(runs);
  const pred = path.join(runs, 'production-run'); const succ = path.join(runs, 'draft-successor-run'); fs.mkdirSync(pred); fs.mkdirSync(succ);
  const oldBinding = storyBinding.buildBinding({ runId: 'production-run', projectId: story.project.id, versionId: story.v1.id, contentHash: story.v1.content_hash, scriptBuilderRoot: story.root, boundAt: '2026-08-30T00:00:00Z', boundBy: 'fixture-human' });
  storyBinding.writeBinding(pred, oldBinding); mode.setProductionMode(pred, mode.PRODUCTION, { setBy: 'Mikko', setAt: '2026-08-30T00:00:00Z' });
  const current = planning.loadCanonicalStory({ scriptBuilderRoot: story.root, projectId: story.project.id, versionId: story.v2.id });
  const currentBinding = storyBinding.buildBinding({ runId: 'draft-successor-run', projectId: story.project.id, versionId: story.v2.id, contentHash: story.v2.content_hash, scriptBuilderRoot: story.root, boundAt: '2026-08-31T00:00:00Z', boundBy: 'draft_bespoke_successor_authority' });
  storyBinding.writeBinding(succ, currentBinding); mode.setProductionMode(succ, mode.DRAFT, { setBy: 'draft_bespoke_successor_authority (agent)', setAt: '2026-08-31T00:00:00Z' });
  const predOutput = path.join(pred, 'directed-draft-r1.mp4'); fs.writeFileSync(predOutput, 'frozen predecessor draft');
  const predRelease = writeJson(path.join(pred, 'release.json'), { schema: 'fixture.release', story: current.story });
  const predHandoff = writeJson(path.join(pred, 'handoff.json'), { schema: 'fixture.handoff', story: current.story });
  const inputs = path.join(succ, 'media', 'draft-inputs'); fs.mkdirSync(inputs, { recursive: true });
  const narration = path.join(inputs, 'narration.wav'); fs.writeFileSync(narration, 'fixture narration');
  const music = path.join(inputs, 'music.wav'); fs.writeFileSync(music, 'fixture music');
  const storyProjection = { project_id: current.story.project_id, version_id: current.story.version_id, content_hash: current.story.content_hash, approval_state: 'approved' };
  const alignmentCore = {
    schema: renderer.NARRATION_ALIGNMENT_SCHEMA, run_id: 'production-run', story: storyProjection,
    source_class: 'HUMAN_DRAFT_NARRATION', narration_sha256: successor.sha256File(narration), narration_duration_measured_ms: 220000,
    timing_authority: 'NARRATION_ALIGNMENT', sections: story.sectionsV2.map((section, index) => ({ section_id: section.id, story_order: index + 1, in_ms: index * 20000, out_ms: (index + 1) * 20000, duration_ms: 20000, script_beat_ids: [`old-${index + 1}`], script_span: section.dialogue })),
  };
  const alignment = { ...alignmentCore, alignment_digest_sha256: renderer.narrationAlignmentDigest(alignmentCore) };
  const alignmentPath = writeJson(path.join(inputs, 'predecessor-alignment.json'), alignment);
  const activeMusic = { decision_id: 'music-fixture', predecessor_decision_id: null, policy: 'FULL_PROGRAMME', status: 'ACTIVE', authority: { type: 'HUMAN', id: 'Mikko' }, decided_at: '2026-08-30T00:00:00Z', basis: 'fixture exact inherited Draft music', music_sha256: successor.sha256File(music), music_path: music, music_duration_measured_ms: 230000 };
  activeMusic.binding_digest_sha256 = renderer.musicDecisionDigest(activeMusic);
  const musicDecision = { schema: 'vidtoolz.visualDraftMusicDecision.v1', run_id: 'production-run', policy_history: [activeMusic], active_decision: activeMusic.decision_id, active_policy: activeMusic.policy, music_asset: { path: music, sha256: successor.sha256File(music) } };
  const musicDecisionPath = writeJson(path.join(inputs, 'predecessor-music-decision.json'), musicDecision);
  const contract = successor.buildSuccessorContract({
    predecessor: { run_id: 'production-run', mode: mode.PRODUCTION, output: { path: predOutput, sha256: successor.sha256File(predOutput) }, handoff: { path: predHandoff, sha256: successor.sha256File(predHandoff) }, release: { path: predRelease, sha256: successor.sha256File(predRelease) } },
    successor: { run_id: 'draft-successor-run', mode: mode.DRAFT }, story: current.story, storyLineage: [story.v1.id, story.v2.id],
    scriptAuthority: { path: storyVersionFile(story, story.v2), sha256: successor.sha256File(storyVersionFile(story, story.v2)), schema: 'vidtoolz-script-builder.story-version.v1' },
    draftInputs: { narration: { path: narration, sha256: successor.sha256File(narration), source_class: 'HUMAN_DRAFT_NARRATION', duration_ms: 220000 }, alignment: { path: alignmentPath, sha256: successor.sha256File(alignmentPath), digest: alignment.alignment_digest_sha256 }, music: { path: music, sha256: successor.sha256File(music), duration_ms: 230000, policy: 'FULL_PROGRAMME', decision_path: musicDecisionPath, decision_sha256: successor.sha256File(musicDecisionPath) } },
    createdAt: '2026-08-31T00:00:00Z',
  });
  writeJson(path.join(succ, successor.SUCCESSOR_FILE), contract);
  return { repo, runs, pred, succ, story, current, contract };
}

function semanticFor(task) {
  let remaining = 20;
  return {
    beats: task.required_beats.map((beat, beatIndex) => {
      const beatsLeft = task.required_beats.length - beatIndex; const count = remaining > beatsLeft ? 2 : 1; remaining -= count;
      return { canonical_beat_id: beat.canonical_beat_id, coverage_decision: 'PLAN_SHOTS', no_visual_reason: null, shots: Array.from({ length: count }, (_, local) => ({
        visual_purpose: `Exact visual purpose ${beatIndex + 1}.${local + 1}`, narrative_function: `Clarify script line ${beatIndex + 1}`, media_type: local === 1 && beatIndex === 0 ? 'INFOGRAPHIC' : 'GENERATED_STILL', generation_mode: local === 1 && beatIndex === 0 ? 'NOT_APPLICABLE' : 'STILL',
        subject: `Distinct subject ${beatIndex + 1}.${local + 1}`, shot_brief: `Distinct vertical concept ${beatIndex + 1}.${local + 1} grounded in the exact current script.`, why_it_serves_story: `Makes current script concept ${beatIndex + 1}.${local + 1} reviewable.`, presenter_relation: 'NONE', duration_target_s: 11,
        research_sensitive: false, research_binding_ids: [], required_constraint_ids: [], visual_assertion: null, camera_required: false, camera_intent: null, continuity_notes: [], alternatives: [], priority: 'NORMAL', demonstration: null, input_artifact_refs: [], quality_constraints: ['static'], candidate_count_request: 1,
        visual_role: local === 1 && beatIndex === 0 ? 'INFOGRAPHIC' : ['SCENE', 'CONCEPTUAL', 'METAPHOR'][beatIndex % 3], repetition_rationale: null,
      })) };
    }),
    coverage_findings: [], continuity_findings: [], redundancy_findings: [], human_attention: [], recommendation: 'PLAN_READY', slot_count_rationale: null,
  };
}

function materializePlanAndRegistry(estate) {
  const task = planning.assembleVisualPlanningTask({ runDir: estate.succ, runId: 'draft-successor-run', taskId: 'fixture-plan', requestedBy: 'fixture', scriptBuilderRoot: estate.story.root }).task;
  const semantic = semanticFor(task); assert.equal(director.validateSemanticOutput(semantic, task).ok, true);
  const plan = director.writePlan(task, semantic, { visualPlanWallClockMs: 10, now: '2026-08-31T00:00:01Z' });
  writeJson(path.join(estate.succ, successor.PLAN_FILE), plan);
  const root = bespoke.evidencePaths(estate.succ); fs.mkdirSync(root.attempts, { recursive: true });
  const registry = { schema: bespoke.REGISTRY_SCHEMA, run_id: 'draft-successor-run', project_id: plan.story.project_id, asset_class: bespoke.ASSET_CLASS, publication_authority: false, final_asset_authority: false, assets: [], attempts: [] };
  for (const slot of plan.draft_bespoke_still_policy.slots) {
    const attemptId = `${slot.slot_id}-attempt-1`; const dir = path.join(root.attempts, attemptId); fs.mkdirSync(dir); const output = path.join(dir, 'still.png'); fs.writeFileSync(output, `unique image ${slot.slot_id}`);
    registry.assets.push({ asset_id: slot.slot_id, slot_id: slot.slot_id, project_id: plan.story.project_id, path: output, sha256: successor.sha256File(output), width: 1080, height: 1920, media_kind: 'IMAGE', asset_class: bespoke.ASSET_CLASS, script_specific: true, temporal_media: false, motion_policy: 'NONE', source_attempt_id: attemptId, visual_plan: { plan_id: plan.plan_id, plan_digest_sha256: plan.plan_digest_sha256, story: plan.story }, script_binding: slot.script_binding, prompt_id: slot.prompt_id, prompt_sha256: slot.prompt_sha256, publication_authority: false, final_asset_authority: false });
    registry.attempts.push({ schema: bespoke.ATTEMPT_SCHEMA, attempt_id: attemptId, slot_id: slot.slot_id, status: 'SUCCEEDED', generator_id: 'fixture-flux', attempt_number: 1, output: { path: output, sha256: successor.sha256File(output), width: 1080, height: 1920 } });
  }
  writeJson(root.registry, registry); return { task, plan, registry, root };
}

test('DBSA01 current approved Script Builder Story is accepted from the stale-bound predecessor project', () => { const e = baseRunEstate(); const current = successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }); assert.equal(current.story.version_id, e.story.v2.id); assert.equal(current.story.approval.state, 'approved'); assert.equal(current.story.approval.approved_by, 'Mikko'); });
test('DBSA02 superseded Story is rejected by canonical current-head task assembly', () => { const e = baseRunEstate(); assert.throws(() => planning.loadCanonicalStory({ scriptBuilderRoot: e.story.root, projectId: e.story.project.id, versionId: e.story.v1.id }), /stale/); });
test('DBSA03 stale predecessor binding is rejected for direct use', () => { const e = baseRunEstate(); errorCode(() => storyBinding.resolveBoundStory(e.pred, { scriptBuilderRoot: e.story.root }), 'STORY_VERSION_SUPERSEDED'); });
test('DBSA04 current Story without approval is rejected', () => { const story = approvedStoryEstate({ approveCurrent: false }); const root = fs.mkdtempSync(path.join(os.tmpdir(), 'unapproved-run-')); const binding = storyBinding.buildBinding({ runId: path.basename(root), projectId: story.project.id, versionId: story.v1.id, contentHash: story.v1.content_hash, scriptBuilderRoot: story.root, boundBy: 'fixture', boundAt: '2026-08-31T00:00:00Z' }); storyBinding.writeBinding(root, binding); errorCode(() => successor.resolveCurrentApprovedStory(root, { scriptBuilderRoot: story.root }), 'DRAFT_SUCCESSOR_CURRENT_STORY_APPROVAL_REQUIRED'); });
test('DBSA05 fabricated current approval hash is rejected', () => { const e = baseRunEstate(); const project = e.story.store.loadProject(e.story.dataRoot, e.story.project.id); project.approved_version.content_hash = 'f'.repeat(64); e.story.store.saveProject(e.story.dataRoot, project); assert.throws(() => successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }), (error) => typeof error.code === 'string'); });
test('DBSA06 a historical release cannot supply current Story approval', () => { const e = baseRunEstate(); Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 3); const v3 = e.story.versions.createVersion(e.story.dataRoot, e.story.project, e.story.sectionsV2.map((section) => ({ ...section, dialogue: `${section.dialogue} Unapproved successor.` })), e.story.config.loadConfig(e.story.dataRoot), {}); writeJson(path.join(e.pred, 'release-claim.json'), { story: { version_id: v3.id, approval_state: 'approved' } }); errorCode(() => successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }), 'DRAFT_SUCCESSOR_CURRENT_STORY_APPROVAL_REQUIRED'); });
test('DBSA07 changed Story content invalidates a previously materialized plan', () => { const e = baseRunEstate(); const { plan } = materializePlanAndRegistry(e); const changed = structuredClone(plan); changed.story.content_hash = 'f'.repeat(64); changed.plan_digest_sha256 = vp.planDigest(changed); assert.equal(vp.validatePlan(changed, { currentStory: e.contract.story }).ok, false); });
test('DBSA08 predecessor lineage mismatch is rejected', () => { const e = baseRunEstate(); const binding = storyBinding.readBinding(e.pred); binding.story.version_id = 'not-an-ancestor'; writeJson(path.join(e.pred, storyBinding.BINDING_FILE), binding); assert.throws(() => successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root })); });
test('DBSA09 wrong-project successor Story is rejected', () => { const e = baseRunEstate(); const contract = structuredClone(e.contract); contract.story.project_id = 'wrong-project'; contract.contract_digest_sha256 = successor.digest((({ contract_digest_sha256, ...rest }) => rest)(contract)); writeJson(path.join(e.succ, successor.SUCCESSOR_FILE), contract); assert.throws(() => successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred })); });
test('DBSA10 changed canonical script bytes are rejected', () => { const e = baseRunEstate(); fs.appendFileSync(storyVersionFile(e.story, e.story.v2), '\nTampered canonical bytes.\n'); assert.throws(() => successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred })); });
test('DBSA11 current Story resolution is deterministic', () => { const e = baseRunEstate(); const a = successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }); const b = successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }); assert.deepEqual(a.story, b.story); assert.deepEqual(a.predecessor_lineage, b.predecessor_lineage); });
test('DBSA12 resolving current Story never rewrites the historical binding', () => { const e = baseRunEstate(); const before = successor.sha256File(path.join(e.pred, storyBinding.BINDING_FILE)); successor.resolveCurrentApprovedStory(e.pred, { scriptBuilderRoot: e.story.root }); assert.equal(successor.sha256File(path.join(e.pred, storyBinding.BINDING_FILE)), before); });

test('DBSA13 Production run cannot select bespoke Draft grammar directly', () => { const e = baseRunEstate(); assert.equal(planning.productionGrammarForRun(e.pred), null); });
test('DBSA14 canonical Draft successor selects bespoke grammar', () => { const e = baseRunEstate(); assert.equal(planning.productionGrammarForRun(e.succ), director.DRAFT_BESPOKE_STILL_GRAMMAR); });
test('DBSA15 Draft successor preserves exact Production predecessor identity', () => { const e = baseRunEstate(); assert.equal(e.contract.predecessor.run_id, 'production-run'); assert.equal(e.contract.predecessor.mode, 'PRODUCTION'); });
test('DBSA16 predecessor Production mode and bytes remain unchanged', () => { const e = baseRunEstate(); const before = successor.sha256File(e.contract.predecessor.output.path); successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }); assert.equal(mode.readProductionMode(e.pred).mode, 'PRODUCTION'); assert.equal(successor.sha256File(e.contract.predecessor.output.path), before); });
test('DBSA17 Draft successor carries no production/publication/final authority', () => { const e = baseRunEstate(); assert.deepEqual({ production: e.contract.policy.production_authority, publication: e.contract.policy.publication_authority, final: e.contract.policy.final_asset_authority }, { production: false, publication: false, final: false }); });
test('DBSA18 fabricated mode override is rejected', () => { const e = baseRunEstate(); const contract = structuredClone(e.contract); contract.successor.mode = 'PRODUCTION'; const core = { ...contract }; delete core.contract_digest_sha256; contract.contract_digest_sha256 = successor.digest(core); writeJson(path.join(e.succ, successor.SUCCESSOR_FILE), contract); errorCode(() => successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_SUCCESSOR_AUTHORITY_ESCALATION'); });
test('DBSA19 duplicate successor discovery is deterministic', () => { const e = baseRunEstate(); const other = path.join(e.runs, 'another-successor'); fs.mkdirSync(other); writeJson(path.join(other, successor.SUCCESSOR_FILE), e.contract); assert.deepEqual(successor.existingSuccessors(e.runs, 'production-run').map((item) => item.name), ['another-successor', 'draft-successor-run']); });
test('DBSA20 successor lineage loop is rejected', () => { const e = baseRunEstate(); const contract = structuredClone(e.contract); contract.predecessor.run_id = 'draft-successor-run'; const core = { ...contract }; delete core.contract_digest_sha256; contract.contract_digest_sha256 = successor.digest(core); writeJson(path.join(e.succ, successor.SUCCESSOR_FILE), contract); errorCode(() => successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_SUCCESSOR_LINEAGE_LOOP'); });

test('DBSA21 current-Story Visual Plan materializes exactly 20 static slots without generation', async () => { const e = baseRunEstate(); const output = await successor.materializeVisualPlan(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, runDirector: async (task) => ({ state: 'AWAITING_HUMAN_REVIEW', visual_plan: director.writePlan(task, semanticFor(task), { visualPlanWallClockMs: 5 }) }) }); assert.equal(output.plan.draft_bespoke_still_policy.planned_visual_slots, 20); assert.equal(fs.existsSync(bespoke.evidencePaths(e.succ).registry), false); });
test('DBSA22 valid registered stills project deterministically into a static handoff', async () => { const e = baseRunEstate(); const { plan } = materializePlanAndRegistry(e); const options = { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, handoffOptions: { allowedRoots: [e.succ, e.pred, e.story.root] } }; const out = await successor.materializeAssemblyAuthorities(e.succ, options); assert.equal(out.state, 'HANDOFF_MATERIALIZED'); assert.equal(out.composition.beats.length, 20); assert.ok(out.composition.beats.every((beat) => beat.layers[0].motion === undefined && beat.layers[0].duration_policy === 'STILL')); assert.equal(out.handoff.production.story.version_id, plan.story.version_id); });
test('DBSA23 unregistered still is rejected', async () => { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); registry.assets.pop(); writeJson(root.registry, registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_REGISTRY_INCOMPLETE'); });
test('DBSA24 asset hash mismatch is rejected', async () => { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); registry.assets[0].sha256 = 'f'.repeat(64); writeJson(root.registry, registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_REGISTRY_ASSET_HASH_MISMATCH'); });
test('DBSA25 wrong slot binding is rejected', async () => { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); registry.assets[0].prompt_id = 'wrong'; writeJson(root.registry, registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_REGISTRY_SLOT_BINDING_INVALID'); });
test('DBSA26 wrong Story binding is rejected', async () => { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); registry.assets[0].script_binding.story_content_hash = 'f'.repeat(64); writeJson(root.registry, registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_REGISTRY_STORY_BINDING_INVALID'); });
test('DBSA27 missing section timeline coverage is rejected', async () => { const e = baseRunEstate(); const built = materializePlanAndRegistry(e); built.plan.draft_bespoke_still_policy.slots = built.plan.draft_bespoke_still_policy.slots.filter((slot) => slot.script_binding.section_id !== 'S11'); built.plan.draft_bespoke_still_policy.planned_visual_slots = built.plan.draft_bespoke_still_policy.slots.length; built.plan.shots = built.plan.shots.filter((shot) => shot.section_ref.section_id !== 'S11'); built.plan.prompts = built.plan.prompts.filter((prompt) => built.plan.shots.some((shot) => shot.shot_id === prompt.shot_id)); built.plan.coverage = built.plan.coverage.map((item) => item.beat_ref.section_id === 'S11' ? { ...item, decision: 'INTENTIONAL_NO_VISUAL', shot_ids: [], reason: 'fixture omission' } : item); built.plan.plan_digest_sha256 = vp.planDigest(built.plan); writeJson(path.join(e.succ, successor.PLAN_FILE), built.plan); built.registry.assets = built.registry.assets.filter((asset) => asset.script_binding.section_id !== 'S11'); built.registry.attempts = built.registry.attempts.filter((attempt) => built.registry.assets.some((asset) => asset.source_attempt_id === attempt.attempt_id)); writeJson(built.root.registry, built.registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_COMPOSITION_SECTION_UNCOVERED'); });
test('DBSA28 fixed COVER and CONTAIN are legal; temporal motion remains rejected', () => { const e = baseRunEstate(); const { plan, registry } = materializePlanAndRegistry(e); const slot = plan.draft_bespoke_still_policy.slots[0]; const asset = bespoke.productionAssetRecord(registry.assets[0], [slot.slot_id]); for (const fit of ['COVER', 'CONTAIN']) { const beat = bespoke.editorBeatFor(slot, slot.slot_id, { beat_id: slot.slot_id, section_id: slot.script_binding.section_id, start_ms: 0, end_ms: 100, fit }); assert.equal(beat.layers[0].fit, fit); } for (const type of ['PAN', 'ZOOM', 'SLOW_SCALE']) { const beat = bespoke.editorBeatFor(slot, slot.slot_id, { beat_id: slot.slot_id, section_id: slot.script_binding.section_id, start_ms: 0, end_ms: 100 }); beat.layers[0].motion = { type }; const model = { schema: composition.SCHEMA, design_package: { path: 'd', sha256: 'a'.repeat(64), schema: 'x' }, approved_visual_plan: { path: 'p', file_sha256: 'b'.repeat(64), plan_id: 'p', digest_sha256: 'c'.repeat(64) }, asset_manifest: { path: 'm', sha256: 'd'.repeat(64) }, coverage: 'FULL_PROGRAMME', expected_beat_count: 1, beats: [beat], forbidden_asset_ids: [] }; errorCode(() => composition.validateComposition(model, [{ section_id: slot.script_binding.section_id, in_ms: 0, out_ms: 100, programme_in_ms: 0, programme_out_ms: 100, script_beat_ids: [slot.slot_id], presenter_authority: 'NOT_APPLICABLE' }], { width: 1080, height: 1920, fps: 30 }, { schema: composition.ASSET_MANIFEST_SCHEMA, assets: [asset] }), 'COMPOSITION_DRAFT_BESPOKE_STILL_MOTION_FORBIDDEN'); } });
test('DBSA29 reveal and animated geometry remain rejected', () => { const e = baseRunEstate(); const { plan } = materializePlanAndRegistry(e); const slot = plan.draft_bespoke_still_policy.slots[0]; const beat = bespoke.editorBeatFor(slot, slot.slot_id, { beat_id: slot.slot_id, section_id: slot.script_binding.section_id, start_ms: 0, end_ms: 100 }); beat.layers[0].reveal = { mode: 'ADDITIVE_PERSIST' }; assert.throws(() => bespoke.staticGeometryEvidence(beat)); beat.layers[0].reveal = undefined; beat.layers[0].geometry.ramp = { end: {}, curve: 'LINEAR' }; assert.throws(() => bespoke.staticGeometryEvidence(beat)); });
test('DBSA30 generated video, I2V/Kling and path injection are rejected', async () => { for (const mutation of ['VIDEO', 'KLING', 'PATH']) { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); if (mutation === 'VIDEO') registry.assets[0].media_kind = 'VIDEO'; if (mutation === 'KLING') registry.attempts[0].generator_id = 'kling-i2v'; if (mutation === 'PATH') { const outside = path.join(e.succ, 'outside.png'); fs.writeFileSync(outside, 'outside'); registry.assets[0].path = outside; registry.assets[0].sha256 = successor.sha256File(outside); } writeJson(root.registry, registry); await assert.rejects(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred })); } });
test('DBSA31 publication/final authority escalation is rejected', async () => { const e = baseRunEstate(); const { root, registry } = materializePlanAndRegistry(e); registry.assets[0].publication_authority = true; writeJson(root.registry, registry); await rejectCode(() => successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred }), 'DRAFT_REGISTRY_SLOT_BINDING_INVALID'); });
test('DBSA32 deterministic registry projection produces identical manifest/composition bytes', async () => { const a = baseRunEstate(); materializePlanAndRegistry(a); const optionsA = { scriptBuilderRoot: a.story.root, predecessorRunDir: a.pred, handoffOptions: { allowedRoots: [a.succ, a.pred, a.story.root] } }; const outA = await successor.materializeAssemblyAuthorities(a.succ, optionsA); const before = { manifest: successor.sha256File(path.join(a.succ, successor.MANIFEST_FILE)), composition: successor.sha256File(path.join(a.succ, successor.COMPOSITION_FILE)) }; const outB = await successor.materializeAssemblyAuthorities(a.succ, optionsA); assert.deepEqual(before, { manifest: successor.sha256File(path.join(a.succ, successor.MANIFEST_FILE)), composition: successor.sha256File(path.join(a.succ, successor.COMPOSITION_FILE)) }); assert.equal(outA.handoff.handoff_id, outB.handoff.handoff_id); });
test('DBSA33 valid Draft release is immutable, current-Story pinned and non-final', async () => { const e = baseRunEstate(); materializePlanAndRegistry(e); const predReleaseBefore = successor.sha256File(e.contract.predecessor.release.path); const out = await successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, handoffOptions: { allowedRoots: [e.succ, e.pred, e.story.root] } }); assert.equal(out.release.story.version_id, e.story.v2.id); assert.equal(out.release.publication_authority, false); assert.equal(out.release.final_asset_authority, false); assert.equal(out.release.presenter_sources.length, 0); assert.equal(successor.sha256File(e.contract.predecessor.release.path), predReleaseBefore); });
test('DBSA34 synthetic narration, Draft music and no final performance survive handoff', async () => { const e = baseRunEstate(); materializePlanAndRegistry(e); const out = await successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, handoffOptions: { allowedRoots: [e.succ, e.pred, e.story.root] } }); assert.equal(out.handoff.narration.source_class, 'HUMAN_DRAFT_NARRATION'); assert.equal(out.handoff.music.policy, 'FULL_PROGRAMME'); assert.equal(out.handoff.presenter.required, false); assert.equal(out.handoff.presenter.mode, 'NOT_APPLICABLE'); });
test('DBSA35 Story change stales release/handoff authority', async () => { const e = baseRunEstate(); materializePlanAndRegistry(e); await successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, handoffOptions: { allowedRoots: [e.succ, e.pred, e.story.root] } }); const contract = readJsonForTest(path.join(e.succ, successor.SUCCESSOR_FILE)); contract.story.content_hash = 'f'.repeat(64); const core = { ...contract }; delete core.contract_digest_sha256; contract.contract_digest_sha256 = successor.digest(core); writeJson(path.join(e.succ, successor.SUCCESSOR_FILE), contract); assert.throws(() => successor.verifySuccessorContract(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred })); });
test('DBSA36 run-ID materialized handoff preserves static composition into Editor projection', async () => { const e = baseRunEstate(); materializePlanAndRegistry(e); const handoffOptions = { allowedRoots: [e.succ, e.pred, e.story.root] }; const out = await successor.materializeAssemblyAuthorities(e.succ, { scriptBuilderRoot: e.story.root, predecessorRunDir: e.pred, handoffOptions }); const consumed = await handoff.consume(e.succ, { ...handoffOptions, dryRun: true, validateRenderer: async (spec) => spec }); assert.equal(consumed.spec.run_id, 'draft-successor-run'); assert.equal(consumed.spec.composition.beats.length, 20); assert.ok(consumed.spec.composition.beats.every((beat) => beat.layers[0].motion === undefined)); assert.equal(out.handoff.provenance.caller_path_authority, false); });

function readJsonForTest(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }

module.exports = { tests: require('./_helpers.js').tests };
