'use strict';
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test, tests } = require('./_helpers.js');
const ownership = require('../scripts/execution-ownership.js');
const ledger = require('../scripts/operator-action-ledger.js');

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ownership-'));
  fs.mkdirSync(path.join(root, 'package-runs/run-1/agents'), { recursive: true });
  const target = { run_id: 'run-1', agent_id: 'story_editor', task_id: 'task-1' };
  return { root, target, actor: ledger.localActorContext({ username: 'mikko' }), taskHash: crypto.createHash('sha256').update('task').digest('hex') };
}
function take(f, extra = {}) {
  const current = ownership.readOwnership(f.root, f.target);
  return ownership.transition(f.root, { ...f.target, action: 'TAKE_MANUAL_CONTROL', next_owner: 'HUMAN', originating_invocation_id: 'story_editor:task-1:1', reason: 'Bounded manual correction.', task_sha256: f.taskHash, artifact_sha256: null, expected_revision: current.revision, expected_state_hash: current.current_state_hash, ...extra }, { actor: f.actor, recordId: 'operator-action-take-1', now: '2026-08-24T09:00:00.000Z' });
}

test('ownership defaults to AUTOMATION and a durable transition is ledger-backed', () => { const f = fixture(); assert.equal(ownership.assertAutomationAllowed(f.root, f.target).current_owner, 'AUTOMATION'); const out = take(f); assert.equal(out.state.current_owner, 'HUMAN'); assert.equal(out.state.revision, 1); assert.equal(ledger.readLedger(f.root, 'run-1').records[0].action, 'TAKE_MANUAL_CONTROL'); assert.throws(() => ownership.assertAutomationAllowed(f.root, f.target), (e) => e.code === 'AUTOMATION_FENCED'); });
test('ownership history is immutable and return chains state and ledger', () => { const f = fixture(); take(f); const before = ownership.readOwnership(f.root, f.target); const out = ownership.transition(f.root, { ...f.target, action: 'RETURN_TO_AUTOMATION', next_owner: 'AUTOMATION', originating_invocation_id: 'story_editor:task-1:1', reason: 'Current bytes revalidated.', task_sha256: f.taskHash, artifact_sha256: null, expected_revision: before.revision, expected_state_hash: before.current_state_hash }, { actor: f.actor, recordId: 'operator-action-return-1', now: '2026-08-24T09:01:00.000Z' }); assert.equal(out.state.current_owner, 'AUTOMATION'); assert.equal(out.state.history.length, 2); assert.equal(out.state.history[1].previous_state_hash, out.state.history[0].state_hash); assert.equal(ledger.readLedger(f.root, 'run-1').records.length, 2); });
test('corruption and broken ledger references fail closed', () => { const f = fixture(); const out = take(f); const p = path.join(f.root, out.state_path); const doc = JSON.parse(fs.readFileSync(p)); doc.history[0].reason = 'tampered'; fs.writeFileSync(p, JSON.stringify(doc)); assert.throws(() => ownership.readOwnership(f.root, f.target), (e) => e.code === 'OWNERSHIP_CORRUPT'); });
test('target isolation and stale revisions are enforced', () => { const f = fixture(); const initial = ownership.readOwnership(f.root, f.target); take(f); assert.equal(ownership.assertAutomationAllowed(f.root, { ...f.target, task_id: 'task-2' }).current_owner, 'AUTOMATION'); assert.throws(() => ownership.transition(f.root, { ...f.target, action: 'RETURN_TO_AUTOMATION', next_owner: 'AUTOMATION', originating_invocation_id: 'story_editor:task-1:1', reason: 'Stale attempt.', task_sha256: f.taskHash, expected_revision: initial.revision, expected_state_hash: initial.current_state_hash }, { actor: f.actor }), (e) => e.code === 'OWNERSHIP_STALE'); });
test('ownership cannot contain approval authority or escape its path', () => { const f = fixture(); take(f); const bytes = fs.readFileSync(ownership.pathsFor(f.root, f.target).statePath, 'utf8'); assert.equal(/approval|approved|approver/i.test(bytes), false); assert.throws(() => ownership.readOwnership(f.root, { ...f.target, task_id: '../escape' }), (e) => e.code === 'OWNERSHIP_TARGET_INVALID'); });
test('ledger append crash leaves a durable fail-closed fence', () => { const f = fixture(), current = ownership.readOwnership(f.root, f.target); assert.throws(() => ownership.transition(f.root, { ...f.target, action: 'TAKE_MANUAL_CONTROL', next_owner: 'HUMAN', originating_invocation_id: 'story_editor:task-1:1', reason: 'Crash-order probe.', task_sha256: f.taskHash, expected_revision: current.revision, expected_state_hash: current.current_state_hash }, { actor: f.actor, recordId: 'operator-action-crash-probe', appendAction: () => { throw new Error('disk full'); } }), /disk full/); assert.throws(() => ownership.readOwnership(f.root, f.target), (e) => e.code === 'OWNERSHIP_LEDGER_REFERENCE_INVALID'); assert.throws(() => ownership.assertAutomationAllowed(f.root, f.target), (e) => e.code === 'OWNERSHIP_LEDGER_REFERENCE_INVALID'); });
test('SUSPENDED is durable orchestration fencing and does not claim compute pause', () => { const f = fixture(), current = ownership.readOwnership(f.root, f.target); const out = ownership.transition(f.root, { ...f.target, action: 'SUSPEND_AUTOMATION', next_owner: 'SUSPENDED', originating_invocation_id: 'story_editor:task-1:1', reason: 'Suspend orchestration; remote compute state is unchanged.', task_sha256: f.taskHash, expected_revision: current.revision, expected_state_hash: current.current_state_hash }, { actor: f.actor, recordId: 'operator-action-suspend-1' }); assert.equal(out.state.current_owner, 'SUSPENDED'); assert.throws(() => ownership.assertAutomationAllowed(f.root, f.target), (e) => e.code === 'AUTOMATION_FENCED'); assert.equal(ledger.readLedger(f.root, 'run-1').records[0].action, 'SUSPEND_AUTOMATION'); });
test('missing state is initial AUTOMATION only without exact ownership history', () => { const f = fixture(); assert.equal(ownership.readOwnership(f.root, f.target).current_owner, 'AUTOMATION'); take(f); fs.unlinkSync(ownership.pathsFor(f.root, f.target).statePath); assert.throws(() => ownership.readOwnership(f.root, f.target), (e) => e.code === 'OWNERSHIP_REQUIRED_MISSING'); assert.throws(() => ownership.assertAutomationAllowed(f.root, f.target), (e) => e.code === 'OWNERSHIP_REQUIRED_MISSING'); assert.equal(ownership.readOwnership(f.root, { ...f.target, task_id: 'task-2' }).current_owner, 'AUTOMATION'); assert.equal(ownership.readOwnership(f.root, { ...f.target, run_id: 'run-2' }).current_owner, 'AUTOMATION'); });
test('missing state after RETURN or SUSPEND history remains fail closed', () => { const returned = fixture(); take(returned); let current = ownership.readOwnership(returned.root, returned.target); ownership.transition(returned.root, { ...returned.target, action: 'RETURN_TO_AUTOMATION', next_owner: 'AUTOMATION', originating_invocation_id: 'story_editor:task-1:1', reason: 'Returned after validation.', task_sha256: returned.taskHash, expected_revision: current.revision, expected_state_hash: current.current_state_hash }, { actor: returned.actor, recordId: 'operator-action-return-delete' }); fs.unlinkSync(ownership.pathsFor(returned.root, returned.target).statePath); assert.throws(() => ownership.readOwnership(returned.root, returned.target), (e) => e.code === 'OWNERSHIP_REQUIRED_MISSING'); const suspended = fixture(); current = ownership.readOwnership(suspended.root, suspended.target); ownership.transition(suspended.root, { ...suspended.target, action: 'SUSPEND_AUTOMATION', next_owner: 'SUSPENDED', originating_invocation_id: 'story_editor:task-1:1', reason: 'Suspend before deletion test.', task_sha256: suspended.taskHash, expected_revision: current.revision, expected_state_hash: current.current_state_hash }, { actor: suspended.actor, recordId: 'operator-action-suspend-delete' }); fs.unlinkSync(ownership.pathsFor(suspended.root, suspended.target).statePath); assert.throws(() => ownership.readOwnership(suspended.root, suspended.target), (e) => e.code === 'OWNERSHIP_REQUIRED_MISSING'); });
test('ledger tamper cannot make a missing ownership state fail open', () => { const f = fixture(); take(f); const statePath = ownership.pathsFor(f.root, f.target).statePath; fs.unlinkSync(statePath); const ledgerPath = ledger.ledgerPaths(f.root, f.target.run_id).ledgerPath; const doc = JSON.parse(fs.readFileSync(ledgerPath)); doc.records[0].target_task_id = 'task-else'; fs.writeFileSync(ledgerPath, JSON.stringify(doc)); assert.throws(() => ownership.readOwnership(f.root, f.target), (e) => e.code === 'OPERATOR_LEDGER_CORRUPT'); });

if (require.main === module) { (async () => { let passed = 0; for (const item of tests) { try { await item.fn(); passed++; console.log(`ok - ${item.name}`); } catch (error) { console.error(`not ok - ${item.name}`); console.error(error); process.exitCode = 1; break; } } console.log(`${passed}/${tests.length} Execution Ownership tests passed`); })(); }
