'use strict';

/*
 * Final Asset Production certification.
 *
 * Fixtures reuse the promoted Final Production harness (real Story, real
 * bespoke Visual Plan, real Directed Draft render, real KEEP approval, real
 * lock and package), then drive the manual asset loop. No image or clip is
 * ever generated by the system: fixtures hand over real ffmpeg-synthesized
 * files exactly as Mikko would hand over a GPT Image download.
 */

const { assert, fs, os, path, test } = require('./_helpers.js');
const crypto = require('node:crypto');
const childProcess = require('node:child_process');

const fplHarness = require('./final-production-lock-package.test.js');
const pkgAuthority = require('../scripts/final-production-package.js');
const production = require('../scripts/final-asset-production.js');
const cli = require('../scripts/final-assets.js');

function shaFile(f) { return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'); }
function readJson(f) { return JSON.parse(fs.readFileSync(f, 'utf8')); }
function writeJson(f, v) { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, `${JSON.stringify(v, null, 2)}\n`); return f; }
function errorCode(fn, code) {
  let got = 'no throw';
  try { fn(); } catch (error) { got = error.code; }
  assert.equal(got, code, `expected ${code}, got ${got}`);
}
const HUMAN = 'Mikko Pakkala';

/* ── real media fixtures (what Mikko would hand over) ────────────────────── */

function ffmpeg(args) {
  const result = childProcess.spawnSync('ffmpeg', ['-v', 'error', '-y', ...args], { timeout: 120000 });
  assert.equal(result.status, 0, `ffmpeg fixture failed: ${(result.stderr || '').toString().slice(0, 200)}`);
}
let mediaRoot = null;
function media() {
  if (mediaRoot) return mediaRoot;
  mediaRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'final-asset-media-'));
  return mediaRoot;
}
/* Every fixture asset must have UNIQUE bytes: the production authority
 * deliberately refuses to bind identical bytes to two different beats, so a
 * shared-colour fixture would trip that guard rather than test the workflow. */
function uniqueColor(label) { return `0x${crypto.createHash('sha256').update(String(label)).digest('hex').slice(0, 6)}`; }
function makeImage(label, options = {}) {
  const file = path.join(media(), `${label}.png`);
  const w = options.width || 1080; const h = options.height || 1920;
  ffmpeg(['-f', 'lavfi', '-i', `color=c=${options.color || uniqueColor(label)}:s=${w}x${h}`, '-frames:v', '1', file]);
  return file;
}
function makeVideo(label, options = {}) {
  const file = path.join(media(), `${label}.mp4`);
  const seconds = options.seconds || 11;
  ffmpeg(['-f', 'lavfi', '-i', `color=c=${options.color || uniqueColor(label)}:s=1080x1920:d=${seconds}`, '-r', '30', '-pix_fmt', 'yuv420p', file]);
  return file;
}

/* ── an estate with a live lock + package ────────────────────────────────── */

async function estateFor(label) {
  const estate = await fplHarness.packagedEstate(`fap-${label}`);
  const visual = readJson(estate.paths.visual);
  const still = visual.beats.find((b) => b.recommended_asset_kind === 'FINAL_STILL_CANDIDATE');
  const video = visual.beats.find((b) => b.recommended_asset_kind === 'FINAL_VIDEO_SOURCE_CANDIDATE');
  return { ...estate, visual, stillBeat: still, videoBeat: video, opts: { scriptBuilderRoot: estate.story.root } };
}

/* ── §5/§6 prompt exposure ───────────────────────────────────────────────── */

test('FAP01 the next action exposes one copy-friendly prompt and the exact beat it belongs to', async () => {
  const e = await estateFor('prompt');
  const next = production.nextAction(e.runDir, e.opts);
  assert.equal(next.phase, 'FINAL_ASSET_PRODUCTION');
  assert.equal(next.complete, false);
  assert.equal(next.task, 'GENERATE_IMAGE');
  assert.equal(next.final_beat_id, 'final-visual-001');
  assert.equal(next.state, 'PROMPT_READY');
  assert.match(next.next_action, /^Generate the final image for beat final-visual-001 in GPT Image using prompt final-image-prompt-final-visual-001/);
  const b = next.briefing;
  // ONE clean field carrying only the production prompt
  assert.equal(typeof b.prompt, 'string');
  assert.ok(b.prompt.length > 400);
  assert.equal(b.prompt.trim().startsWith('Vertical 9:16'), true);
  assert.equal(/[{}\[\]"]:/.test(b.prompt), false, 'the prompt field carries no JSON fragments');
  // full machine metadata preserved separately
  assert.equal(b.prompt_id, 'final-image-prompt-final-visual-001');
  assert.equal(b.geometry.aspect_ratio, '9:16');
  assert.ok(b.safe_regions.text_safe_band);
  assert.ok(b.beat.locked_script_line.length > 0);
  assert.ok(production.ASSET_KINDS.includes(b.role.effective));
  assert.equal(b.role.overridable, true);
  assert.ok(b.production_notes.some((n) => /MANUAL|manually/.test(n)));
  assert.match(b.next_human_action, /generate the image manually/);
  assert.equal(b.state, 'PROMPT_READY');
});

test('FAP02 an infographic beat exposes its exact allowed text with the prompt', async () => {
  const e = await estateFor('infographic');
  const ctx = production.context(e.runDir, e.opts);
  const info = e.visual.beats.find((b) => b.infographic_contract);
  if (!info) {
    // this fixture plan has no text-bearing role; prove the non-text contract instead
    const b = production.beatBriefing(ctx, e.visual.beats[0].final_beat_id);
    assert.equal(b.infographic, null);
    assert.match(b.prompt, /NO text, letters, numerals/);
    assert.ok(b.production_notes.some((n) => /no text of any kind/.test(n)));
    return;
  }
  const b = production.beatBriefing(ctx, info.final_beat_id);
  assert.deepEqual(b.infographic.exact_allowed_text, info.infographic_contract.exact_allowed_text);
  assert.ok(b.infographic.hierarchy && b.infographic.typography_constraints && b.infographic.safe_regions);
  assert.match(b.prompt, /render EXACTLY and ONLY this text/);
});

/* ── §38 Case A — still path ─────────────────────────────────────────────── */

test('FAP03 Case A still: ingest -> GENERATED -> human select -> FINAL_ASSET_SELECTED, no I2V', async () => {
  const e = await estateFor('case-a');
  const beat = e.stillBeat.final_beat_id;
  const file = makeImage('case-a-still');
  const ingested = production.ingestImage(e.runDir, beat, file, e.opts);
  assert.equal(ingested.state, 'GENERATED');
  assert.equal(ingested.beat_state, 'GENERATED');
  assert.equal(ingested.asset.schema, 'vidtoolz.finalVisualAsset.v1');
  assert.equal(ingested.asset.disposition, 'CANDIDATE');
  assert.equal(ingested.asset.selected, false);
  assert.equal(ingested.asset.final_asset_authority, false);
  assert.equal(ingested.asset.media.sha256, shaFile(file));
  assert.deepEqual([ingested.asset.media.width, ingested.asset.media.height], [1080, 1920]);
  // GENERATED is not SELECTED
  let status = production.beatStatus(production.context(e.runDir, e.opts), production.beatFor(production.context(e.runDir, e.opts), beat).entry);
  assert.equal(status.selected_image_sha256, null);
  assert.equal(status.complete, false);
  assert.equal(status.task.task, 'SELECT_IMAGE');
  // human selection completes a still beat
  const selected = production.selectImage(e.runDir, beat, ingested.asset.media.sha256.slice(0, 12), { ...e.opts, authority: HUMAN });
  assert.equal(selected.state, 'FINAL_ASSET_SELECTED');
  const ctx = production.context(e.runDir, e.opts);
  const entry = production.beatFor(ctx, beat).entry;
  assert.equal(entry.final_asset.kind, 'FINAL_STILL');
  assert.equal(entry.final_asset.sha256, shaFile(file));
  assert.equal(entry.selection_authority.type, 'HUMAN');
  assert.equal(entry.selection_authority.id, HUMAN);
  assert.equal(entry.motion_prompt, null, 'a still beat never needs an I2V prompt');
  errorCode(() => production.prepareMotionPrompt(e.runDir, beat, e.opts), 'FINAL_ASSET_NOT_A_VIDEO_SOURCE');
});

/* ── §38 Case B — video-source path ──────────────────────────────────────── */

test('FAP04 Case B video: image -> select -> I2V_READY -> image-bound prompt -> clip -> select -> complete', async () => {
  const e = await estateFor('case-b');
  const beat = e.videoBeat.final_beat_id;
  const image = makeImage('case-b-image');
  const ing = production.ingestImage(e.runDir, beat, image, e.opts);
  assert.equal(ing.beat_state, 'GENERATED');
  // no authoritative I2V prompt before selection
  errorCode(() => production.prepareMotionPrompt(e.runDir, beat, e.opts), 'FINAL_ASSET_I2V_REQUIRES_SELECTED_IMAGE');
  errorCode(() => production.motionBriefing(e.runDir, beat, e.opts), 'FINAL_ASSET_MOTION_PROMPT_MISSING');
  const sel = production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(sel.state, 'SELECTED_IMAGE', 'a selected image is provenance, not the final asset, for a video beat');
  // clip cannot be ingested before the prompt exists
  const clip = makeVideo('case-b-clip', { seconds: Math.max(2, Math.round(e.videoBeat.duration_ms / 1000)) });
  errorCode(() => production.ingestVideo(e.runDir, beat, clip, e.opts), 'FINAL_ASSET_VIDEO_REQUIRES_MOTION_PROMPT');
  // image-bound prompt
  const prepared = production.prepareMotionPrompt(e.runDir, beat, e.opts);
  assert.equal(prepared.state, 'I2V_READY');
  assert.equal(prepared.record.schema, 'vidtoolz.finalImageToVideoPrompt.v1');
  assert.equal(prepared.record.selected_image.sha256, shaFile(image));
  assert.equal(prepared.record.binds_selected_image, true);
  assert.equal(prepared.record.prompt_version, 1);
  assert.ok(prepared.record.authoritative_prompt.length > 60);
  assert.equal(prepared.record.final_asset_authority, false);
  assert.match(prepared.record.generation_method, /MANUAL/);
  const brief = production.motionBriefing(e.runDir, beat, e.opts);
  assert.equal(typeof brief.prompt, 'string');
  assert.equal(brief.source_image.sha256, shaFile(image));
  assert.ok(brief.negative_constraints.length >= 3);
  // clip ingest, then explicit selection
  const vin = production.ingestVideo(e.runDir, beat, clip, e.opts);
  assert.equal(vin.state, 'VIDEO_GENERATED');
  assert.equal(vin.asset.media_kind, 'VIDEO');
  assert.equal(vin.asset.source_image.sha256, shaFile(image));
  assert.equal(vin.asset.selected, false);
  const ctxMid = production.context(e.runDir, e.opts);
  assert.equal(production.normalizedState(production.beatFor(ctxMid, beat).entry), 'VIDEO_GENERATED');
  const vsel = production.selectVideo(e.runDir, beat, vin.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(vsel.state, 'FINAL_ASSET_SELECTED');
  assert.equal(vsel.final_asset.kind, 'FINAL_VIDEO');
  assert.equal(vsel.final_asset.sha256, shaFile(clip));
  assert.equal(vsel.final_asset.provenance.source_image_sha256, shaFile(image));
  assert.equal(vsel.final_asset.provenance.motion_prompt_digest_sha256, prepared.record.motion_prompt_digest_sha256);
});

/* ── §38 Case C / D — candidates, alternates, rejection ──────────────────── */

test('FAP05 Case C: two candidates, B selected, A preserved unselected', async () => {
  const e = await estateFor('case-c');
  const beat = e.stillBeat.final_beat_id;
  const a = makeImage('case-c-a', { color: 'maroon' });
  const b = makeImage('case-c-b', { color: 'olive' });
  const ia = production.ingestImage(e.runDir, beat, a, e.opts);
  const ib = production.ingestImage(e.runDir, beat, b, e.opts);
  assert.notEqual(ia.asset.media.sha256, ib.asset.media.sha256);
  production.selectImage(e.runDir, beat, ib.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const ctx = production.context(e.runDir, e.opts);
  const entry = production.beatFor(ctx, beat).entry;
  assert.equal(entry.selected_image.sha256, shaFile(b));
  const cands = entry.candidates.filter((c) => c.media_kind === 'IMAGE');
  assert.equal(cands.length, 2, 'both candidates preserved');
  assert.equal(cands.find((c) => c.sha256 === shaFile(a)).disposition, 'CANDIDATE');
  assert.equal(cands.find((c) => c.sha256 === shaFile(b)).disposition, 'SELECTED');
  assert.ok(fs.existsSync(path.resolve(e.runDir, cands.find((c) => c.sha256 === shaFile(a)).path)), 'the unselected candidate bytes remain on disk');
  // an alternate can be marked without becoming current
  const alt = production.keepAsAlternate(e.runDir, beat, shaFile(a), 'IMAGE', { ...e.opts, authority: HUMAN });
  assert.equal(alt.alternate.disposition, 'KEEP_AS_ALTERNATE');
  assert.equal(production.beatFor(production.context(e.runDir, e.opts), beat).entry.selected_image.sha256, shaFile(b));
});

test('FAP06 Case D: reject then replace; rejected candidates never become current', async () => {
  const e = await estateFor('case-d');
  const beat = e.stillBeat.final_beat_id;
  const a = makeImage('case-d-a', { color: 'purple' });
  const ia = production.ingestImage(e.runDir, beat, a, e.opts);
  const rej = production.rejectCandidate(e.runDir, beat, ia.asset.media.sha256, 'IMAGE', { ...e.opts, authority: HUMAN, note: 'wrong subject entirely' });
  assert.equal(rej.rejected.disposition, 'REJECTED');
  assert.equal(rej.rejected.rejection.note, 'wrong subject entirely');
  assert.equal(rej.state, 'PROMPT_READY', 'all candidates rejected: the beat needs a new generation');
  assert.ok(fs.existsSync(path.resolve(e.runDir, rej.rejected.path)), 'rejected bytes are preserved');
  errorCode(() => production.selectImage(e.runDir, beat, ia.asset.media.sha256, { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_CANDIDATE_REJECTED');
  // rejection may omit a note
  const b = makeImage('case-d-b', { color: 'green' });
  const ib = production.ingestImage(e.runDir, beat, b, e.opts);
  const sel = production.selectImage(e.runDir, beat, ib.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(sel.state, 'FINAL_ASSET_SELECTED');
  // the selected candidate cannot then be rejected out from under the beat
  errorCode(() => production.rejectCandidate(e.runDir, beat, ib.asset.media.sha256, 'IMAGE', { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_CANNOT_REJECT_SELECTED');
  const status = production.beatStatus(production.context(e.runDir, e.opts), production.beatFor(production.context(e.runDir, e.opts), beat).entry);
  assert.equal(status.rejected, 1);
  assert.equal(status.complete, true);
});

/* ── §38 Case E — re-selection invalidates downstream authority ───────────── */

test('FAP07 Case E: re-selecting the image stales the I2V prompt and its clips', async () => {
  const e = await estateFor('case-e');
  const beat = e.videoBeat.final_beat_id;
  const imageA = makeImage('case-e-a', { color: 'navy' });
  const imageB = makeImage('case-e-b', { color: 'orange' });
  const ia = production.ingestImage(e.runDir, beat, imageA, e.opts);
  production.selectImage(e.runDir, beat, ia.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const promptA = production.prepareMotionPrompt(e.runDir, beat, e.opts);
  const clipA = makeVideo('case-e-clip-a');
  const va = production.ingestVideo(e.runDir, beat, clipA, e.opts);
  assert.equal(va.state, 'VIDEO_GENERATED');
  // now Mikko picks a different image
  const ib = production.ingestImage(e.runDir, beat, imageB, e.opts);
  const resel = production.selectImage(e.runDir, beat, ib.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(resel.reselection, true);
  assert.equal(resel.state, 'SELECTED_IMAGE');
  assert.ok(resel.staled.some((s) => s.kind === 'MOTION_PROMPT'));
  const ctx = production.context(e.runDir, e.opts);
  const entry = production.beatFor(ctx, beat).entry;
  assert.equal(entry.motion_prompt, null, 'the old image-bound prompt is no longer current');
  assert.equal((entry.stale_motion_prompts || []).length, 1);
  assert.equal(entry.selected_video, null);
  const clipCand = entry.candidates.find((c) => c.media_kind === 'VIDEO');
  assert.equal(clipCand.disposition, 'SUPERSEDED');
  assert.match(clipCand.stale_reason, /superseded source image/);
  // the superseded clip can never become the final asset
  errorCode(() => production.selectVideo(e.runDir, beat, va.asset.media.sha256, { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_CANDIDATE_SUPERSEDED');
  // the historical prompt record is preserved, not rewritten
  assert.ok(fs.existsSync(promptA.path));
  assert.equal(readJson(promptA.path).selected_image.sha256, shaFile(imageA));
  // a new prompt is required, and it binds image B with a bumped version
  const promptB = production.prepareMotionPrompt(e.runDir, beat, e.opts);
  assert.equal(promptB.record.selected_image.sha256, shaFile(imageB));
  assert.equal(promptB.record.prompt_version, 2);
  assert.notEqual(promptB.record.motion_prompt_digest_sha256, promptA.record.motion_prompt_digest_sha256);
});

/* ── §38 Case F — role override ──────────────────────────────────────────── */

test('FAP08 Case F: a human can turn a still beat into a video source and back', async () => {
  const e = await estateFor('case-f');
  const beat = e.stillBeat.final_beat_id;
  const image = makeImage('case-f-image');
  const ing = production.ingestImage(e.runDir, beat, image, e.opts);
  const sel = production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(sel.state, 'FINAL_ASSET_SELECTED', 'still by recommendation');
  // human overrides to a video source: the beat is no longer complete
  const toVideo = production.setRole(e.runDir, beat, 'FINAL_VIDEO_SOURCE_CANDIDATE', { ...e.opts, authority: HUMAN, note: 'this one wants a slow push' });
  assert.equal(toVideo.role_before, 'FINAL_STILL_CANDIDATE');
  assert.equal(toVideo.role_after, 'FINAL_VIDEO_SOURCE_CANDIDATE');
  assert.equal(toVideo.state, 'SELECTED_IMAGE');
  const ctx1 = production.context(e.runDir, e.opts);
  const entry1 = production.beatFor(ctx1, beat).entry;
  assert.equal(entry1.final_asset, null, 'a video beat is not complete on an image alone');
  assert.equal(entry1.role_override.authority.type, 'HUMAN');
  assert.equal(entry1.role_override.recommended_was, 'FINAL_STILL_CANDIDATE');
  // the I2V workflow is now unlocked
  const prepared = production.prepareMotionPrompt(e.runDir, beat, e.opts);
  assert.equal(prepared.state, 'I2V_READY');
  // and switching back makes the selected image satisfy the beat again
  const back = production.setRole(e.runDir, beat, 'FINAL_STILL_CANDIDATE', { ...e.opts, authority: HUMAN });
  assert.equal(back.state, 'FINAL_ASSET_SELECTED');
  assert.equal(production.beatFor(production.context(e.runDir, e.opts), beat).entry.final_asset.kind, 'FINAL_STILL');
  // roles never change silently
  errorCode(() => production.setRole(e.runDir, beat, 'FINAL_VIDEO_SOURCE_CANDIDATE', e.opts), 'FINAL_ASSET_HUMAN_AUTHORITY_REQUIRED');
  errorCode(() => production.setRole(e.runDir, beat, 'SOMETHING_ELSE', { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_ROLE_INVALID');
});

/* ── §29 duplicate / cross-beat ──────────────────────────────────────────── */

test('FAP09 identical bytes re-ingest as ALREADY_REGISTERED and can never cross-bind to another beat', async () => {
  const e = await estateFor('dupes');
  const beat = e.stillBeat.final_beat_id;
  const other = e.visual.beats.find((b) => b.final_beat_id !== beat).final_beat_id;
  const image = makeImage('dupes-image');
  const first = production.ingestImage(e.runDir, beat, image, e.opts);
  const again = production.ingestImage(e.runDir, beat, image, e.opts);
  assert.equal(again.state, 'ALREADY_REGISTERED');
  assert.equal(again.asset.asset_id, first.asset.asset_id);
  const ctx = production.context(e.runDir, e.opts);
  assert.equal(production.beatFor(ctx, beat).entry.candidates.filter((c) => c.media_kind === 'IMAGE').length, 1, 'no duplicate asset authority');
  errorCode(() => production.ingestImage(e.runDir, other, image, e.opts), 'FINAL_ASSET_CROSS_BEAT_BINDING');
});

/* ── §9 technical validation is not creative approval ────────────────────── */

test('FAP10 technical validation rejects unusable media but never approves creatively', async () => {
  const e = await estateFor('validation');
  const beat = e.stillBeat.final_beat_id;
  // corrupt / non-media file
  const corrupt = path.join(media(), 'corrupt.png');
  fs.writeFileSync(corrupt, 'this is definitely not a PNG');
  errorCode(() => production.ingestImage(e.runDir, beat, corrupt, e.opts), 'FINAL_ASSET_IMAGE_UNREADABLE');
  // missing file
  errorCode(() => production.ingestImage(e.runDir, beat, path.join(media(), 'nope.png'), e.opts), 'FINAL_ASSET_FILE_MISSING');
  // too small to use
  const tiny = makeImage('tiny', { width: 128, height: 228 });
  errorCode(() => production.ingestImage(e.runDir, beat, tiny, e.opts), 'FINAL_ASSET_IMAGE_DIMENSIONS_UNUSABLE');
  // wrong aspect: accepted as a candidate with a WARNING — the tool does not
  // overrule Mikko's chosen frame on arithmetic
  const wide = makeImage('wide', { width: 1920, height: 1080 });
  const ing = production.ingestImage(e.runDir, beat, wide, e.opts);
  assert.equal(ing.state, 'GENERATED');
  assert.ok(ing.warnings.some((w) => /aspect/.test(w)));
  // and it is still only a candidate
  assert.equal(ing.asset.selected, false);
  assert.equal(production.beatFor(production.context(e.runDir, e.opts), beat).entry.selected_image, null);
});

/* ── §23/§24/§34 queue, progress, next action ────────────────────────────── */

test('FAP11 the work queue and progress counts resolve across all 20 beats', async () => {
  const e = await estateFor('queue');
  const before = production.workQueue(e.runDir, e.opts);
  assert.equal(before.progress.total_beats, 20);
  assert.equal(before.progress.prompt_ready, 20);
  assert.equal(before.progress.final_complete, 0);
  assert.equal(before.progress.image_selected, 0);
  assert.equal(before.current_beat, 'final-visual-001');
  assert.equal(before.waiting_on_manual_generation.length, 20);
  assert.equal(before.final_assets_complete, false);
  assert.equal(before.publication_approved, false);
  // complete one still beat and watch the projections move
  const beat = e.stillBeat.final_beat_id;
  const image = makeImage('queue-image');
  const ing = production.ingestImage(e.runDir, beat, image, e.opts);
  const mid = production.workQueue(e.runDir, e.opts);
  assert.equal(mid.progress.generated, 1);
  assert.equal(mid.waiting_on_mikko_decision.some((t) => t.final_beat_id === beat && t.task === 'SELECT_IMAGE'), true);
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const after = production.workQueue(e.runDir, e.opts);
  assert.equal(after.progress.final_complete, 1);
  assert.equal(after.progress.image_selected, 1);
  assert.equal(after.completed[0].final_beat_id, beat);
  assert.equal(after.completed[0].kind, 'FINAL_STILL');
  assert.equal(after.beats.find((b) => b.final_beat_id === beat).task, null);
  // the resolver never skips an unresolved human choice
  const video = e.videoBeat.final_beat_id;
  const vimg = makeImage('queue-video-image');
  production.ingestImage(e.runDir, video, vimg, e.opts);
  const q = production.workQueue(e.runDir, e.opts);
  const row = q.beats.find((b) => b.final_beat_id === video);
  assert.equal(row.task.task, 'SELECT_IMAGE');
  assert.equal(row.task.waiting_on, 'MIKKO_DECISION');
});

test('FAP12 next-action resolves each stage of the loop in dependency order', async () => {
  const e = await estateFor('next-stages');
  const beat = e.videoBeat.final_beat_id;
  // drive every other beat to complete so the video beat is the head of the queue
  for (const spec of e.visual.beats) {
    if (spec.final_beat_id === beat) continue;
    const img = makeImage(`stage-${spec.final_beat_id}`);
    const ing = production.ingestImage(e.runDir, spec.final_beat_id, img, e.opts);
    if (spec.recommended_asset_kind === 'FINAL_VIDEO_SOURCE_CANDIDATE') {
      production.setRole(e.runDir, spec.final_beat_id, 'FINAL_STILL_CANDIDATE', { ...e.opts, authority: HUMAN });
    }
    production.selectImage(e.runDir, spec.final_beat_id, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  }
  assert.equal(production.nextAction(e.runDir, e.opts).task, 'GENERATE_IMAGE');
  const img = makeImage('next-stage-image');
  const ing = production.ingestImage(e.runDir, beat, img, e.opts);
  assert.equal(production.nextAction(e.runDir, e.opts).task, 'SELECT_IMAGE');
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(production.nextAction(e.runDir, e.opts).task, 'PREPARE_I2V_PROMPT');
  production.prepareMotionPrompt(e.runDir, beat, e.opts);
  assert.equal(production.nextAction(e.runDir, e.opts).task, 'GENERATE_KLING_MANUALLY');
  const clip = makeVideo('next-stage-clip');
  const vin = production.ingestVideo(e.runDir, beat, clip, e.opts);
  assert.equal(production.nextAction(e.runDir, e.opts).task, 'SELECT_VIDEO');
  production.selectVideo(e.runDir, beat, vin.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const done = production.nextAction(e.runDir, e.opts);
  assert.equal(done.complete, true);
  assert.match(done.next_action, /all 20 final visual assets are selected/);
  assert.equal(production.workQueue(e.runDir, e.opts).final_assets_complete, true);
});

/* ── §33 Resolve blueprint projection ────────────────────────────────────── */

test('FAP13 selected assets project into the Resolve blueprint without mutating it', async () => {
  const e = await estateFor('projection');
  const blueprintShaBefore = shaFile(e.paths.blueprint);
  const lockShaBefore = shaFile(e.lock_path);
  const beat = e.stillBeat.final_beat_id;
  const image = makeImage('projection-image');
  const ing = production.ingestImage(e.runDir, beat, image, e.opts);
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const projected = production.projectResolveAssets(e.runDir, e.opts);
  assert.equal(projected.projection.schema, 'vidtoolz.finalResolveAssetProjection.v1');
  assert.equal(projected.projection.blueprint_mutated, false);
  assert.equal(projected.projection.resolved_beats, 1);
  assert.equal(projected.projection.placeholder_beats, 19);
  const resolved = projected.projection.timeline.find((t) => t.final_beat_id === beat);
  assert.equal(resolved.visual_placeholder.state, 'FINAL_ASSET_SELECTED');
  assert.equal(resolved.visual_placeholder.sha256, shaFile(image));
  assert.equal(resolved.visual_placeholder.kind, 'FINAL_STILL');
  const other = projected.projection.timeline.find((t) => t.final_beat_id !== beat);
  assert.equal(other.visual_placeholder.state, 'AWAITING_FINAL_ASSET_SELECTION');
  assert.equal(other.visual_placeholder.sha256, null);
  // the immutable blueprint and lock are untouched, and no final edit is created
  assert.equal(shaFile(e.paths.blueprint), blueprintShaBefore);
  assert.equal(shaFile(e.lock_path), lockShaBefore);
  assert.equal(projected.projection.final_edit_complete, false);
  assert.equal(projected.projection.publication_authority, false);
});

/* ── §37 hostile matrix ──────────────────────────────────────────────────── */

test('FAP14 hostile: no lock, no package, wrong run, unknown beat, altered package all fail closed', async () => {
  // (1) no lock
  const noLock = await fplHarness.approvedEstate('fap-nolock');
  errorCode(() => production.nextAction(noLock.runDir, { scriptBuilderRoot: noLock.story.root }), 'FINAL_LOCK_MISSING');
  // (2) lock but no package
  const noPkg = await fplHarness.lockedEstate('fap-nopkg');
  errorCode(() => production.nextAction(noPkg.runDir, { scriptBuilderRoot: noPkg.story.root }), 'FINAL_ASSET_PACKAGE_MISSING');
  const e = await estateFor('hostile-basics');
  // (3) nonexistent beat
  errorCode(() => production.beatBriefing(production.context(e.runDir, e.opts), 'final-visual-999'), 'FINAL_ASSET_BEAT_UNKNOWN');
  errorCode(() => production.ingestImage(e.runDir, 'final-visual-999', makeImage('hostile-basics-img'), e.opts), 'FINAL_ASSET_BEAT_UNKNOWN');
  // (4)/(5) altered package / altered prompt
  const visual = readJson(e.paths.visual);
  visual.beats[0].final_image_prompt = `${visual.beats[0].final_image_prompt} tampered`;
  writeJson(e.paths.visual, visual);
  errorCode(() => production.nextAction(e.runDir, e.opts), 'FINAL_ASSET_PACKAGE_STALE');
});

test('FAP15 hostile: caller cannot supply authority — no fake SHA, no fabricated selection, no machine selector', async () => {
  const e = await estateFor('hostile-authority');
  const beat = e.stillBeat.final_beat_id;
  const image = makeImage('hostile-authority-img');
  const ing = production.ingestImage(e.runDir, beat, image, e.opts);
  // (6) a caller-supplied SHA is not authority: the asset hash is computed, and
  // selecting by a hash that is not a registered candidate is refused
  errorCode(() => production.selectImage(e.runDir, beat, 'f'.repeat(64), { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_CANDIDATE_UNKNOWN');
  assert.equal(ing.asset.media.sha256, shaFile(image), 'the hash is computed from bytes, never accepted from the caller');
  // (12)/(13) selection requires a HUMAN authority and refuses a machine one
  errorCode(() => production.selectImage(e.runDir, beat, ing.asset.media.sha256, e.opts), 'FINAL_ASSET_HUMAN_AUTHORITY_REQUIRED');
  for (const bad of ['MACHINE_SELECTOR', 'machine', 'auto-selector', 'agent:claude', 'tool']) {
    errorCode(() => production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: bad }), 'FINAL_ASSET_HUMAN_AUTHORITY_REQUIRED');
  }
  // (11) GENERATED is never treated as SELECTED
  const status = production.beatStatus(production.context(e.runDir, e.opts), production.beatFor(production.context(e.runDir, e.opts), beat).entry);
  assert.equal(status.state, 'GENERATED');
  assert.equal(status.selected_image_sha256, null);
  assert.equal(status.complete, false);
  // (14) selected asset bytes moving invalidates the selection attempt
  const stored = path.resolve(e.runDir, ing.asset.media.path);
  fs.appendFileSync(stored, 'tampered');
  errorCode(() => production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_SELECTED_HASH_MISMATCH');
});

test('FAP16 hostile: Kling authority cannot be forged, mis-sourced or escalated', async () => {
  const e = await estateFor('hostile-kling');
  const beat = e.videoBeat.final_beat_id;
  const still = e.stillBeat.final_beat_id;
  // (15) I2V before selection
  const img = makeImage('hostile-kling-img');
  const ing = production.ingestImage(e.runDir, beat, img, e.opts);
  errorCode(() => production.prepareMotionPrompt(e.runDir, beat, e.opts), 'FINAL_ASSET_I2V_REQUIRES_SELECTED_IMAGE');
  // (18) a clip without I2V authority
  const clip = makeVideo('hostile-kling-clip');
  errorCode(() => production.ingestVideo(e.runDir, beat, clip, e.opts), 'FINAL_ASSET_VIDEO_REQUIRES_SELECTED_IMAGE');
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  errorCode(() => production.ingestVideo(e.runDir, beat, clip, e.opts), 'FINAL_ASSET_VIDEO_REQUIRES_MOTION_PROMPT');
  // a still beat can never hold a motion prompt or a clip
  errorCode(() => production.prepareMotionPrompt(e.runDir, still, e.opts), 'FINAL_ASSET_NOT_A_VIDEO_SOURCE');
  errorCode(() => production.ingestVideo(e.runDir, still, clip, e.opts), 'FINAL_ASSET_NOT_A_VIDEO_SOURCE');
  production.prepareMotionPrompt(e.runDir, beat, e.opts);
  // (20) corrupt video
  const badVideo = path.join(media(), 'corrupt.mp4');
  fs.writeFileSync(badVideo, 'not a video at all');
  errorCode(() => production.ingestVideo(e.runDir, beat, badVideo, e.opts), 'FINAL_ASSET_VIDEO_UNREADABLE');
  // (21) selected clip bytes moving
  const vin = production.ingestVideo(e.runDir, beat, clip, e.opts);
  const storedClip = path.resolve(e.runDir, vin.asset.media.path);
  fs.appendFileSync(storedClip, 'tampered');
  errorCode(() => production.selectVideo(e.runDir, beat, vin.asset.media.sha256, { ...e.opts, authority: HUMAN }), 'FINAL_ASSET_SELECTED_HASH_MISMATCH');
  // (13) machine authority refused for clips too
  errorCode(() => production.selectVideo(e.runDir, beat, vin.asset.media.sha256, { ...e.opts, authority: 'MACHINE_SELECTOR' }), 'FINAL_ASSET_HUMAN_AUTHORITY_REQUIRED');
});

test('FAP17 hostile: asset ingest and selection never mutate the lock, package or approved Draft', async () => {
  const e = await estateFor('hostile-immutable');
  const before = {
    lock: shaFile(e.lock_path),
    pkg: shaFile(e.paths.package),
    visual: shaFile(e.paths.visual),
    performance: shaFile(e.paths.performance),
    music: shaFile(e.paths.music),
    blueprint: shaFile(e.paths.blueprint),
    draft: shaFile(path.join(e.runDir, 'media/directed-draft-assembly/directed-draft-r1.mp4')),
    review: shaFile(require('../scripts/draft-review-intake.js').reviewFile(e.runDir, 'mikko-approved')),
  };
  const beat = e.videoBeat.final_beat_id;
  const img = makeImage('hostile-immutable-img');
  const ing = production.ingestImage(e.runDir, beat, img, e.opts);
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  production.prepareMotionPrompt(e.runDir, beat, e.opts);
  const clip = makeVideo('hostile-immutable-clip');
  const vin = production.ingestVideo(e.runDir, beat, clip, e.opts);
  production.selectVideo(e.runDir, beat, vin.asset.media.sha256, { ...e.opts, authority: HUMAN });
  production.projectResolveAssets(e.runDir, e.opts);
  // (26)/(27)/(28) nothing upstream moved
  assert.equal(shaFile(e.lock_path), before.lock, 'lock unchanged');
  assert.equal(shaFile(e.paths.package), before.pkg, 'package unchanged');
  assert.equal(shaFile(e.paths.visual), before.visual, 'visual package unchanged');
  assert.equal(shaFile(e.paths.performance), before.performance, 'performance package unchanged');
  assert.equal(shaFile(e.paths.music), before.music, 'music brief unchanged');
  assert.equal(shaFile(e.paths.blueprint), before.blueprint, 'Resolve blueprint unchanged');
  assert.equal(shaFile(path.join(e.runDir, 'media/directed-draft-assembly/directed-draft-r1.mp4')), before.draft, 'approved Draft unchanged');
  assert.equal(shaFile(require('../scripts/draft-review-intake.js').reviewFile(e.runDir, 'mikko-approved')), before.review, 'approval unchanged');
  // (24)/(25) no publication or QC authority anywhere in the asset records
  const asset = readJson(path.resolve(e.runDir, production.beatFor(production.context(e.runDir, e.opts), beat).entry.candidates[0].record_path));
  assert.equal(asset.publication_authority, false);
  assert.equal(asset.final_asset_authority, false);
  const q = production.workQueue(e.runDir, e.opts);
  assert.equal(q.publication_approved, false);
  assert.equal(q.final_qc_pass, false);
  assert.equal(q.final_edit_complete, false);
  assert.equal(fs.existsSync(path.join(e.runDir, 'final-master.mp4')), false);
});

test('FAP18 hostile: a Draft still cannot be silently registered as a Final asset, and completion needs the real chain', async () => {
  const e = await estateFor('hostile-draft-asset');
  const beat = e.videoBeat.final_beat_id;
  // (29) a Draft bespoke still never becomes a Final asset by proximity: it is
  // not registered anywhere in the Final asset authority, and the only way any
  // file becomes a candidate is an explicit human ingest that mints a NEW
  // immutable record bound to the FINAL beat and the FINAL prompt.
  const draftStill = path.join(e.runDir, 'media', 'draft-bespoke-stills', `${e.slots[0].slot_id}.png`);
  assert.ok(fs.existsSync(draftStill), 'the Draft still exists on disk');
  const ctxBefore = production.context(e.runDir, e.opts);
  assert.equal(ctxBefore.tracker.beats.every((entry) => !(entry.candidates || []).length), true, 'no Draft asset is registered as a Final candidate');
  const draftSha = shaFile(draftStill);
  assert.equal(ctxBefore.tracker.beats.some((entry) => (entry.candidates || []).some((c) => c.sha256 === draftSha)), false);
  // and a Draft artifact that is not real publication-grade media is refused
  // outright by technical validation (this fixture's stills are placeholders)
  errorCode(() => production.ingestImage(e.runDir, beat, draftStill, e.opts), 'FINAL_ASSET_IMAGE_UNREADABLE');
  // a genuine manually generated image becomes a candidate bound to the FINAL prompt
  const img = makeImage('hostile-draft-asset-final');
  const ing = production.ingestImage(e.runDir, beat, img, e.opts);
  assert.equal(ing.asset.media_kind, 'IMAGE');
  assert.equal(ing.asset.final_beat_id, beat);
  assert.equal(ing.asset.prompt.prompt_id, e.videoBeat.final_image_prompt_id, 'bound to the FINAL prompt, not the Draft prompt');
  assert.equal(ing.asset.generation.method, 'MANUAL_GPT_IMAGE');
  assert.equal(ing.asset.selected, false);
  assert.equal(ing.asset.final_asset_authority, false);
  assert.equal(ing.beat_state, 'GENERATED', 'still only a candidate');
  // (23) completion requires the whole chain for a video beat
  production.selectImage(e.runDir, beat, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  const status = production.beatStatus(production.context(e.runDir, e.opts), production.beatFor(production.context(e.runDir, e.opts), beat).entry);
  assert.equal(status.complete, false, 'a selected image alone never completes a video beat');
  assert.equal(status.task.task, 'PREPARE_I2V_PROMPT');
  assert.equal(production.workQueue(e.runDir, e.opts).final_assets_complete, false);
});

/* ── §27 CLI operability ─────────────────────────────────────────────────── */

test('FAP19 the CLI drives the whole loop with only a run, a beat and a file', async () => {
  const e = await estateFor('cli');
  const args = (...extra) => ['--run-id', path.basename(e.runDir), '--repo', e.repo, ...extra];
  // next: prompt exposed in human-readable form
  const next = await cli.run(args().length ? ['next', ...args()] : ['next']);
  assert.match(next.text, /NEXT TASK: GENERATE_IMAGE/);
  assert.match(next.text, /PROMPT \(final-image-prompt-final-visual-001\)/);
  assert.match(next.text, /Vertical 9:16/);
  assert.equal(next.value.final_beat_id, 'final-visual-001');
  // prompt for a specific beat
  const beat = e.stillBeat.final_beat_id;
  const prompt = await cli.run(['prompt', ...args('--beat', beat)]);
  assert.match(prompt.text, new RegExp(`BEAT ${beat}`));
  assert.equal(typeof prompt.value.prompt, 'string');
  // ingest -> the CLI tells Mikko the next exact command
  const image = makeImage('cli-image');
  const ingested = await cli.run(['ingest-image', ...args('--beat', beat, '--file', image)]);
  assert.match(ingested.text, /INGESTED final-asset-/);
  assert.match(ingested.text, /GENERATED is NOT selected/);
  assert.match(ingested.text, /Next: final-assets select-image/);
  // select by short sha prefix
  const selected = await cli.run(['select-image', ...args('--beat', beat, '--candidate', ingested.value.asset.media.sha256.slice(0, 12), '--authority', HUMAN)]);
  assert.match(selected.text, /SELECTED image/);
  assert.match(selected.text, /this still beat is now complete/);
  // queue + progress render as a table, not raw JSON
  const queue = await cli.run(['queue', ...args()]);
  assert.match(queue.text, /FINAL ASSET PRODUCTION/);
  assert.match(queue.text, /BEAT\s+STATE\s+ROLE/);
  assert.match(queue.text, /progress\s+1\/20 complete/);
  const progress = await cli.run(['progress', ...args()]);
  assert.match(progress.text, /final_complete\s+1/);
  // project
  const projected = await cli.run(['project', ...args()]);
  assert.match(projected.text, /RESOLVE ASSET PROJECTION written \(1 resolved, 19 still placeholders\)/);
  assert.match(projected.text, /blueprint mutated: false/);
  // argument hygiene: the caller may not pass a hash, asset id or authority object
  errorCode(() => cli.parseArgs(['ingest-image', '--run-id', 'x', '--beat', 'b', '--file', 'f', '--sha256', 'abc']), 'FINAL_ASSETS_ARGUMENT_INVALID');
  errorCode(() => cli.parseArgs(['select-image', '--run-id', 'x', '--beat', 'b']), 'FINAL_ASSETS_ARGUMENT_INVALID');
  errorCode(() => cli.parseArgs(['nope', '--run-id', 'x']), 'FINAL_ASSETS_COMMAND_INVALID');
  assert.match(cli.usage(), /never calls GPT Image or Kling/);
});

test('FAP20 the CLI Kling path exposes the image-bound prompt and refuses before selection', async () => {
  const e = await estateFor('cli-kling');
  const beat = e.videoBeat.final_beat_id;
  const args = (...extra) => ['--run-id', path.basename(e.runDir), '--repo', e.repo, ...extra];
  const image = makeImage('cli-kling-image');
  const ing = await cli.run(['ingest-image', ...args('--beat', beat, '--file', image)]);
  await assert.rejects(() => cli.run(['kling-prompt', ...args('--beat', beat)]), (error) => error.code === 'FINAL_ASSET_I2V_REQUIRES_SELECTED_IMAGE');
  await cli.run(['select-image', ...args('--beat', beat, '--candidate', ing.value.asset.media.sha256.slice(0, 12), '--authority', HUMAN)]);
  const kling = await cli.run(['kling-prompt', ...args('--beat', beat)]);
  assert.match(kling.text, /KLING PROMPT — beat/);
  assert.match(kling.text, new RegExp(`image sha256   ${shaFile(image)}`));
  assert.match(kling.text, /do not allow:/);
  assert.equal(kling.value.source_image.sha256, shaFile(image));
  const clip = makeVideo('cli-kling-clip');
  const vin = await cli.run(['ingest-video', ...args('--beat', beat, '--file', clip)]);
  assert.match(vin.text, /VIDEO_GENERATED is NOT selected/);
  const vsel = await cli.run(['select-video', ...args('--beat', beat, '--candidate', vin.value.asset.media.sha256.slice(0, 12), '--authority', HUMAN)]);
  assert.match(vsel.text, /SELECTED final clip/);
  assert.match(vsel.text, /provenance  source image/);
});

test('FAP21 the state machine keeps GENERATED, SELECTED_IMAGE and FINAL_ASSET_SELECTED distinct', async () => {
  assert.deepEqual(production.BEAT_STATES, ['PROMPT_READY', 'GENERATED', 'SELECTED_IMAGE', 'I2V_READY', 'VIDEO_GENERATED', 'FINAL_ASSET_SELECTED', 'BLOCKED']);
  assert.deepEqual(production.DISPOSITIONS, ['CANDIDATE', 'KEEP_AS_ALTERNATE', 'REJECTED', 'SELECTED', 'SUPERSEDED']);
  // the historical spelling still reads correctly
  assert.equal(production.normalizedState({ state: 'SELECTED' }), 'SELECTED_IMAGE');
  assert.equal(production.normalizedState({ state: 'GENERATED' }), 'GENERATED');
  const e = await estateFor('states');
  const video = e.videoBeat.final_beat_id;
  const img = makeImage('states-img');
  const ing = production.ingestImage(e.runDir, video, img, e.opts);
  assert.equal(ing.beat_state, 'GENERATED');
  const sel = production.selectImage(e.runDir, video, ing.asset.media.sha256, { ...e.opts, authority: HUMAN });
  assert.equal(sel.state, 'SELECTED_IMAGE');
  assert.notEqual(sel.state, 'FINAL_ASSET_SELECTED', 'a video beat is not complete on a selected image');
  // and the promoted package resolver still understands the run
  const legacy = pkgAuthority.nextActions(e.runDir, e.opts);
  assert.ok(legacy.ready.length + legacy.waiting_on_mikko.length > 0);
  assert.equal(legacy.publication_approved, false);
});

module.exports = { tests: require('./_helpers.js').tests, estateFor, makeImage, makeVideo };
