'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test, tests } = require('./_helpers.js');
const ledger = require('../scripts/operator-action-ledger.js');

function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'operator-ledger-')); fs.mkdirSync(path.join(root, 'package-runs/run-1'), { recursive: true }); return { root, runId: 'run-1', actor: ledger.localActorContext({ username: 'mikko' }) }; }
function input(over = {}) { return { action: 'RETRY', target_agent_role: 'story_editor', target_invocation_id: 'story_editor:task-1:1', target_task_id: 'task-1', target_artifact: null, action_scope: 'INVOCATION_RETRY', reason: 'Retry the exact failed invocation.', requested_parameters: { preserve_lane: true, preserve_model: true }, prior_execution_owner: 'AUTOMATION', resulting_execution_owner: 'AUTOMATION', supersedes: null, result_status: 'COMPLETED', ...over }; }
function append(f, over = {}, options = {}) { return ledger.appendOperatorAction(f.root, f.runId, input(over), { actor: f.actor, ...options }); }
function raw(f) { return JSON.parse(fs.readFileSync(ledger.ledgerPaths(f.root, f.runId).ledgerPath, 'utf8')); }
function writeRaw(f, value) { fs.writeFileSync(ledger.ledgerPaths(f.root, f.runId).ledgerPath, JSON.stringify(value)); }

test('operator ledger appends a valid first record without approval authority', () => { const f = fixture(); const out = append(f); assert.equal(out.record.previous_record_hash, null); assert.equal(ledger.readLedger(f.root, f.runId).records.length, 1); assert.equal(JSON.stringify(out.record).includes('approval'), false); });
test('operator ledger second record chains to the first', () => { const f = fixture(); const one = append(f); const two = append(f, { action: 'CANCEL', action_scope: 'INVOCATION_CANCEL', result_status: 'NOT_SUPPORTED', resulting_execution_owner: 'SUSPENDED' }); assert.equal(two.record.previous_record_hash, one.record.record_hash); });
test('operator ledger detects body and previous-hash tampering', () => { for (const mutation of [(x) => { x.records[0].reason = 'tampered'; }, (x) => { x.records[1].previous_record_hash = null; }]) { const f = fixture(); append(f); append(f, { action: 'CANCEL', action_scope: 'INVOCATION_CANCEL', result_status: 'NOT_SUPPORTED', resulting_execution_owner: 'SUSPENDED' }); const value = raw(f); mutation(value); writeRaw(f, value); assert.throws(() => ledger.readLedger(f.root, f.runId), (e) => e.code === 'OPERATOR_LEDGER_CORRUPT'); } });
test('operator ledger detects deletion and reordering', () => { for (const mutation of [(x) => x.records.pop(), (x) => x.records.reverse()]) { const f = fixture(); append(f); append(f, { action: 'CANCEL', action_scope: 'INVOCATION_CANCEL', result_status: 'NOT_SUPPORTED', resulting_execution_owner: 'SUSPENDED' }); const value = raw(f); mutation(value); writeRaw(f, value); assert.throws(() => ledger.readLedger(f.root, f.runId), (e) => e.code === 'OPERATOR_LEDGER_CORRUPT'); } });
test('operator ledger rejects invalid target and action', () => { const f = fixture(); assert.throws(() => append(f, { target_invocation_id: '../escape' }), (e) => e.code === 'OPERATOR_LEDGER_TARGET_INVALID'); assert.throws(() => append(f, { action: 'PUBLISH' }), (e) => e.code === 'OPERATOR_LEDGER_ACTION_INVALID'); });
test('operator ledger rejects missing or client-shaped actor', () => { const f = fixture(); assert.throws(() => ledger.appendOperatorAction(f.root, f.runId, input()), (e) => e.code === 'OPERATOR_LEDGER_ACTOR_INVALID'); assert.throws(() => ledger.appendOperatorAction(f.root, f.runId, input(), { actor: { identity_type: 'CLIENT', identity: 'mikko' } }), (e) => e.code === 'OPERATOR_LEDGER_ACTOR_INVALID'); });
test('operator ledger rejects path escape and symlinked authority directory', () => { const f = fixture(); assert.throws(() => ledger.readLedger(f.root, '../escape'), (e) => e.code === 'OPERATOR_LEDGER_TARGET_INVALID'); const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'operator-ledger-out-')); fs.rmSync(path.join(f.root, 'package-runs/run-1'), { recursive: true }); fs.symlinkSync(outside, path.join(f.root, 'package-runs/run-1')); assert.throws(() => append(f), (e) => e.code === 'OPERATOR_LEDGER_PATH_INVALID'); });
test('operator ledger refuses a parallel writer lock', () => { const f = fixture(); const paths = ledger.ledgerPaths(f.root, f.runId); fs.mkdirSync(paths.agentsDir, { recursive: true }); fs.writeFileSync(paths.lockPath, JSON.stringify({ token: 'held' })); assert.throws(() => append(f), (e) => e.code === 'OPERATOR_LEDGER_BUSY'); });
test('operator ledger rejects approval metadata anywhere in an action', () => { const f = fixture(); assert.throws(() => append(f, { requested_parameters: { approval_binding: { approved_by: 'Mikko' } } }), (e) => e.code === 'OPERATOR_LEDGER_RECORD_INVALID'); assert.equal(fs.existsSync(ledger.ledgerPaths(f.root, f.runId).ledgerPath), false); });

if (require.main === module) { let passed = 0; for (const item of tests) { try { item.fn(); passed++; console.log(`ok - ${item.name}`); } catch (error) { console.error(`not ok - ${item.name}`); console.error(error); process.exitCode = 1; break; } } console.log(`${passed}/${tests.length} Operator Action Ledger tests passed`); }
