'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test } = require('./_helpers.js');
const boundary = require('../scripts/presenter-boundary-review.js');
const prepare = require('../scripts/prepare-presenter-boundary-review.js');
const sourceAuthority = require('../scripts/presenter-source-authority.js');

const NOW = '2026-08-26T13:00:00.000Z';
const H = boundary.sha256;
const STORY = { project_id: 'story-p', version_id: 'story-v', content_hash: H('story'), approval_state: 'approved' };
const PLAN = { plan_id: 'vp2', version: 2, digest_sha256: H('vp2'), approval_state: 'approved' };
const HUMAN = { type: 'HUMAN', id: 'Mikko Pakkala' };
function base(count = 11) {
  const masters = [{ master_id: 'A', path: '/media/A.mp4', sha256: H('A'), duration_ms: 120000, section_ids: Array.from({ length: count }, (_, i) => `S${i + 1}`), captured_framing: 'actual A' }];
  const sections = Array.from({ length: count }, (_, i) => ({ section_id: `S${i + 1}`, recording_unit_id: `U${i + 1}`, story_order: i + 1, approved_script_excerpt: `approved ${i + 1}`, master_id: 'A', planned_framing: 'planned A', captured_framing: 'actual A', proposal: { in_ms: i * 10000, out_ms: (i + 1) * 10000, boundary_class: 'MACHINE_INFERRED_PROVISIONAL', method: 'test' } }));
  return boundary.createSession({ run_id: 'run-1', production_mode: 'PRODUCTION', story: STORY, visual_plan: PLAN, visual_plan_approval_evidence: { verified: true }, predecessor_review: { path: 'HUMAN-REVIEW-PERFORMANCE-V1.json', sha256: H('old'), verdict: 'KEEP ALL' }, masters, sections, prepared_at: NOW, prepared_by: 'test' });
}
function confirmAll(session, count = session.sections.length) { let next = session; for (const item of session.sections.slice(0, count)) next = boundary.confirmSection(next, { section_id: item.section_id, actor: HUMAN, confirmed_at: NOW }); return next; }

test('BR-1 machine proposals remain provisional authority', () => { const session = base(); assert.equal(session.sections.every((s) => s.state === 'PROVISIONAL' && s.boundary_class === 'MACHINE_INFERRED_PROVISIONAL'), true); assert.throws(() => boundary.buildSuccessorReview(session), (e) => e.code === 'BOUNDARY_CONFIRMATION_INCOMPLETE'); });
test('BR-2 agent cannot confirm a section', () => { assert.throws(() => boundary.confirmSection(base(), { section_id: 'S1', actor: { type: 'HUMAN', id: 'Claude agent' }, confirmed_at: NOW }), (e) => e.code === 'BOUNDARY_HUMAN_IDENTITY_REQUIRED'); });
test('BR-3 verified human click binds both exact integer-ms edges', () => { const session = boundary.confirmSection(base(), { section_id: 'S1', actor: HUMAN, confirmed_at: NOW }); const s = session.sections[0]; assert.equal(s.state, 'CONFIRMED'); assert.equal(s.boundary_class, 'HUMAN_CONFIRMED'); assert.equal(s.current.in_ms, 0); assert.equal(s.current.out_ms, 10000); assert.match(s.confirmation_digest_sha256, /^[a-f0-9]{64}$/); });
test('BR-4 adjustment invalidates prior confirmation and remains provisional', () => { const confirmed = boundary.confirmSection(base(), { section_id: 'S1', actor: HUMAN, confirmed_at: NOW }); const adjusted = boundary.adjustBoundary(confirmed, { section_id: 'S1', edge: 'out_ms', delta_ms: 250 }); assert.equal(adjusted.sections[0].state, 'PROVISIONAL'); assert.equal(adjusted.sections[0].confirmation_digest_sha256, null); });
test('BR-5 reset restores exact machine proposal without granting authority', () => { const adjusted = boundary.adjustBoundary(base(), { section_id: 'S1', edge: 'out_ms', delta_ms: 250 }); const reset = boundary.resetProposal(adjusted, 'S1'); assert.deepEqual(reset.sections[0].current, { in_ms: 0, out_ms: 10000 }); assert.equal(reset.sections[0].boundary_class, 'MACHINE_INFERRED_PROVISIONAL'); });
test('BR-6 negative, zero, float and beyond-duration boundaries fail closed', () => { for (const value of [{ in_ms: -1, out_ms: 2 }, { in_ms: 2, out_ms: 2 }, { in_ms: 0.5, out_ms: 2 }, { in_ms: 0, out_ms: 120001 }]) assert.throws(() => boundary.validateInterval(value, 120000)); });
test('BR-7 changed Story or VP2 invalidates confirmations', () => { const session = confirmAll(base(), 1); assert.equal(boundary.validateSession(session, { currentStory: { ...STORY, content_hash: H('drift') } }).ok, false); assert.equal(boundary.validateSession(session, { currentVisualPlan: { ...PLAN, digest_sha256: H('drift') } }).ok, false); });
test('BR-8 changed master identity invalidates the session digest and lineage', () => { const session = base(); session.masters[0].sha256 = H('changed'); const result = boundary.validateSession(session); assert.equal(result.ok, false); assert.ok(result.errors.some((e) => e.code === 'BOUNDARY_SESSION_DIGEST_INVALID')); });
test('BR-9 overlapping confirmed intervals fail', () => { let session = base(2); session = boundary.confirmSection(session, { section_id: 'S1', actor: HUMAN, confirmed_at: NOW }); session = boundary.adjustBoundary(session, { section_id: 'S2', edge: 'in_ms', delta_ms: -1000 }); assert.throws(() => boundary.confirmSection(session, { section_id: 'S2', actor: HUMAN, confirmed_at: NOW }), (e) => e.code === 'BOUNDARY_CONFIRMATION_INVALID'); });
test('BR-10 10/11 cannot emit successor review', () => { assert.throws(() => boundary.buildSuccessorReview(confirmAll(base(), 10)), (e) => e.code === 'BOUNDARY_CONFIRMATION_INCOMPLETE'); });
test('BR-11 11/11 emits append-only successor bound to predecessor, Story, VP2 and masters', () => { const review = boundary.buildSuccessorReview(confirmAll(base()), { review_id: 'review-v2' }); assert.equal(review.segments.length, 11); assert.equal(review.predecessor_review.sha256, H('old')); assert.deepEqual(review.story, STORY); assert.deepEqual(review.visual_plan, PLAN); assert.equal(review.binding_digest_sha256, boundary.successorDigest(review)); });
test('BR-12 tampered successor digest is rejected from Claude release', () => { const review = boundary.buildSuccessorReview(confirmAll(base())); review.segments[0].out_ms += 1; const packet = boundary.buildClaudeReleasePacket({ state: 'ASSEMBLY_ELIGIBLE', ready: true, sources: [] }, review, { music_policy: { state: 'RESOLVED' } }); assert.ok(packet.blockers.some((b) => b.code === 'SUCCESSOR_REVIEW_INVALID')); });
test('BR-13 provisional boundary cannot enter Claude release', () => { const review = boundary.buildSuccessorReview(confirmAll(base())); review.segments[0].boundary_class = 'MACHINE_INFERRED_PROVISIONAL'; review.binding_digest_sha256 = boundary.successorDigest(review); const packet = boundary.buildClaudeReleasePacket({ state: 'ASSEMBLY_ELIGIBLE', ready: true, sources: [] }, review, { music_policy: { state: 'RESOLVED' } }); assert.ok(packet.blockers.some((b) => b.code === 'PROVISIONAL_BOUNDARY_FORBIDDEN')); });
test('BR-14 unresolved music policy is a typed handoff blocker, not a guessed choice', () => { const review = boundary.buildSuccessorReview(confirmAll(base())); const packet = boundary.buildClaudeReleasePacket({ state: 'ASSEMBLY_ELIGIBLE', ready: true, sources: [] }, review, { music_policy: { state: 'MUSIC_DURATION_POLICY_HUMAN_DECISION_REQUIRED' } }); assert.ok(packet.blockers.some((b) => b.code === 'MUSIC_DURATION_POLICY_HUMAN_DECISION_REQUIRED')); });
test('BR-15 silence parser and weighted proposal are deterministic assistance only', () => { const silence = { intervals: prepare.parseSilences('[silencedetect] silence_start: 9.0\n[silencedetect] silence_end: 11.0 | silence_duration: 2.0\n[silencedetect] silence_start: 19.0\n[silencedetect] silence_end: 21.0 | silence_duration: 2.0') }; const out = prepare.proposeIntervals(30000, [{ approved_dialogue: 'one' }, { approved_dialogue: 'two' }, { approved_dialogue: 'three' }], silence); assert.deepEqual(out, [{ in_ms: 0, out_ms: 10000 }, { in_ms: 10000, out_ms: 20000 }, { in_ms: 20000, out_ms: 30000 }]); });
test('BR-16 all 11 human confirmations project to canonical ASSEMBLY_ELIGIBLE', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'boundary-eligible-')); const mediaPath = path.join(dir, 'A.mp4'); fs.writeFileSync(mediaPath, 'A');
  const session = confirmAll(base()); const successor = boundary.buildSuccessorReview(session, { review_id: 'review-v2' });
  const units = session.sections.map((s) => ({ recording_unit_id: s.recording_unit_id, section_id: s.section_id, order: s.story_order }));
  const sidecar = { schema: 'vidtoolz.humanCaptureSidecar.v1', origin: 'HUMAN', capture_class: 'REAL_HUMAN_PERFORMANCE', quality_class: 'PROOF_CAPTURE', run_id: 'run-1', master_id: 'A', media_sha256: H('A'), story: STORY, visual_plan: PLAN, device_provenance: { host: 'presto', video: { identity: '@video' }, audio: { identity: '@audio' } } };
  const sidecarPath = path.join(dir, 'A.json'); const sidecarText = `${JSON.stringify(sidecar)}\n`; fs.writeFileSync(sidecarPath, sidecarText);
  let authority = sourceAuthority.createAuthority({ run_id: 'run-1', production_mode: 'PRODUCTION', story: STORY, visual_plan: PLAN, recording_units: units, created_at: NOW, created_by: 'test' });
  authority = sourceAuthority.registerMaster(authority, { master_id: 'A', source_kind: 'BATCH_MASTER', quality_class: 'PROOF_CAPTURE', origin: 'HUMAN', capture_class: 'REAL_HUMAN_PERFORMANCE', run_id: 'run-1', story: STORY, visual_plan: PLAN, captured_at: NOW, capture_profile: 'presto-webcam-1080p30-mic', device_provenance: sidecar.device_provenance, media: { path: mediaPath, sha256: H('A'), byte_size: 1, duration_s: 120, video: { codec: 'h264' }, audio: { codec: 'aac' } }, sidecar: { path: sidecarPath, sha256: H(sidecarText) }, sections_declared: session.sections.map((s) => s.section_id) });
  authority = boundary.applySuccessorReview(sourceAuthority, authority, successor);
  const options = { currentRunId: 'run-1', currentStory: STORY, currentVisualPlan: PLAN, allowedHumanIds: ['Mikko Pakkala'], knownNonHumanMediaHashes: [], mediaProbe: () => ({ ok: true, actual_sha256: H('A'), byte_size: 1, duration_s: 120, video: { codec: 'h264' }, audio: { codec: 'aac' } }) };
  const handoff = sourceAuthority.buildEditorHandoff(authority, options); assert.equal(handoff.state, 'ASSEMBLY_ELIGIBLE', JSON.stringify(handoff.blockers)); assert.equal(handoff.sources.length, 11);
});
