'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test } = require('./_helpers.js');
const authority = require('../scripts/presenter-source-authority.js');
const capture = require('../supervised-capture.js');
const dshow = require('../scripts/directshow-device-resolver.js');
const readiness = require('../scripts/production-capture-readiness.js');

const NOW = '2026-08-26T12:00:00.000Z';
const H = authority.sha256;
const STORY = { project_id: 'story-project', version_id: 'story-version', content_hash: H('dialogue'), approval_state: 'approved' };
const PLAN = { plan_id: 'visual-plan-v2', version: 2, digest_sha256: H('vp2'), approval_state: 'approved' };
const UNITS = [1, 2, 3].map((n) => ({ recording_unit_id: `unit-${n}`, section_id: `section-${n}`, order: n, dialogue_sha256: H(`section-${n}`) }));

function clone(value) { return structuredClone(value); }
function reseal(doc) { doc.authority_digest_sha256 = authority.authorityDigest(doc); return doc; }
function fixture(label = 'valid') {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `tier3-${label}-`));
  const mediaPath = path.join(dir, 'capture-master.mp4');
  const bytes = Buffer.from(`real-human-media-${label}`); fs.writeFileSync(mediaPath, bytes);
  const master = {
    master_id: `master-${label}`, source_kind: 'BATCH_MASTER', quality_class: 'PROOF_CAPTURE', origin: 'HUMAN', capture_class: 'REAL_HUMAN_PERFORMANCE',
    run_id: 'run-1', story: STORY, visual_plan: PLAN, captured_at: NOW, capture_profile: 'presto-webcam-1080p30-mic',
    device_provenance: { host: 'presto', video: { identity: '@device_cm_video' }, audio: { identity: '@device_cm_audio' } },
    media: { path: mediaPath, sha256: H(bytes), byte_size: bytes.length, duration_s: 12, video: { codec: 'h264', width: 1920, height: 1080 }, audio: { codec: 'aac', sample_rate: 48000, channels: 2 } },
    sidecar: { path: path.join(dir, 'capture-master.json'), sha256: '' }, sections_declared: ['section-1', 'section-2', 'section-3'],
  };
  const sidecar = { schema: 'vidtoolz.humanCaptureSidecar.v1', origin: 'HUMAN', capture_class: 'REAL_HUMAN_PERFORMANCE', quality_class: 'PROOF_CAPTURE', run_id: 'run-1', master_id: master.master_id, media_sha256: master.media.sha256, story: STORY, visual_plan: PLAN, device_provenance: master.device_provenance };
  const sidecarText = `${JSON.stringify(sidecar, null, 2)}\n`; fs.writeFileSync(master.sidecar.path, sidecarText); master.sidecar.sha256 = H(sidecarText);
  const probe = (media) => ({ ok: true, actual_sha256: H(fs.readFileSync(media.path)), byte_size: fs.statSync(media.path).size, duration_s: 12, video: media.video, audio: media.audio });
  let doc = authority.createAuthority({ run_id: 'run-1', production_mode: 'PRODUCTION', story: STORY, visual_plan: PLAN, recording_units: UNITS, created_at: NOW, created_by: 'test' });
  doc = authority.registerMaster(doc, master);
  return { dir, bytes, master, sidecar, probe, doc };
}
function segment(master, n, over = {}) {
  const start = (n - 1) * 4; return {
    segment_id: `segment-${n}`, master_id: master.master_id, source_master_sha256: master.media.sha256,
    recording_unit_id: `unit-${n}`, section_id: `section-${n}`, in_s: start, out_s: start + 4, duration_s: 4,
    story: STORY, visual_plan: PLAN, framing_setup: n === 3 ? 'tight-cu' : 'baseline-mcu', status: 'ACTIVE',
    boundary: { class: 'HUMAN_CONFIRMED', asserted_by: 'MIKKO', asserted_at: NOW, evidence_ref: 'boundary-review.json', evidence_sha256: H('boundaries') }, ...over,
  };
}
function complete(label = 'complete') {
  const f = fixture(label); let doc = f.doc;
  for (let n = 1; n <= 3; n++) doc = authority.registerSegment(doc, segment(f.master, n));
  doc = authority.bindHumanReview(doc, { review_id: 'review-1', run_id: 'run-1', verdict: 'KEEP_ALL', reviewer: { type: 'HUMAN', id: 'MIKKO' }, reviewed_at: NOW, story: STORY, visual_plan: PLAN, masters: [{ master_id: f.master.master_id, media_sha256: f.master.media.sha256, sections_declared: f.master.sections_declared }], review_binding_sha256: '' });
  for (let n = 1; n <= 3; n++) doc = authority.selectSegment(doc, { selection_id: `selection-${n}`, review_id: 'review-1', segment_id: `segment-${n}`, master_id: f.master.master_id, media_sha256: f.master.media.sha256, section_id: `section-${n}`, selector: { type: 'HUMAN', id: 'MIKKO' }, selected_at: NOW, status: 'ACTIVE', selection_binding_sha256: '' });
  return { ...f, doc };
}
function options(f) { return { currentRunId: 'run-1', currentStory: STORY, currentVisualPlan: PLAN, allowedHumanIds: ['MIKKO'], knownNonHumanMediaHashes: [], mediaProbe: f.probe, requireCompleteCoverage: true }; }

test('T3-1 valid batch master maps one immutable source to multiple selected sections', () => { const f = complete('batch'); const result = authority.validateAuthority(f.doc, options(f)); assert.equal(result.ok, true, JSON.stringify(result.errors)); assert.equal(authority.buildEditorHandoff(f.doc, options(f)).sources.length, 3); });
test('T3-2 single-section take uses the same source and segment authority model', () => { const f = fixture('single'); f.doc.masters[0].source_kind = 'SECTION_TAKE'; f.doc.masters[0].sections_declared = ['section-1']; f.master.sections_declared = ['section-1']; f.doc.recording_units = [UNITS[0]]; f.doc = reseal(f.doc); f.doc = authority.registerSegment(f.doc, segment(f.master, 1, { in_s: 0, out_s: 12, duration_s: 12, boundary: { class: 'CAPTURE_EVENT_BOUND', asserted_by: 'capture-controller', asserted_at: NOW, evidence_ref: f.master.sidecar.path, evidence_sha256: f.master.sidecar.sha256 } })); f.doc = authority.bindHumanReview(f.doc, { review_id: 'r', run_id: 'run-1', verdict: 'KEEP_ALL', reviewer: { type: 'HUMAN', id: 'MIKKO' }, reviewed_at: NOW, story: STORY, visual_plan: PLAN, masters: [{ master_id: f.master.master_id, media_sha256: f.master.media.sha256, sections_declared: ['section-1'] }] }); f.doc = authority.selectSegment(f.doc, { selection_id: 's', review_id: 'r', segment_id: 'segment-1', master_id: f.master.master_id, media_sha256: f.master.media.sha256, section_id: 'section-1', selector: { type: 'HUMAN', id: 'MIKKO' }, selected_at: NOW, status: 'ACTIVE' }); assert.equal(authority.validateAuthority(f.doc, options(f)).ok, true); });
test('T3-3 changed master bytes invalidate registration and handoff', () => { const f = complete('mutation'); fs.appendFileSync(f.master.media.path, 'changed'); const result = authority.validateAuthority(f.doc, options(f)); assert.ok(result.errors.some((e) => e.code === 'MASTER_MEDIA_MUTATED')); assert.equal(authority.buildEditorHandoff(f.doc, options(f)).ready, false); });
test('T3-4 wrong run, Story, and Visual Plan each fail closed', () => { for (const [field, value, code] of [['run_id', 'wrong', 'MASTER_LINEAGE_INVALID'], ['story', { ...STORY, version_id: 'wrong' }, 'MASTER_LINEAGE_INVALID'], ['visual_plan', { ...PLAN, digest_sha256: H('wrong') }, 'MASTER_LINEAGE_INVALID']]) { const f = complete(`lineage-${field}`); f.doc.masters[0][field] = value; reseal(f.doc); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === code)); } });
test('T3-5 malformed, negative, zero, and out-of-range intervals fail', () => { for (const over of [{ in_s: -1 }, { out_s: 0 }, { in_s: 5, out_s: 4 }, { out_s: 13 }, { duration_s: 7 }]) { const f = complete(`interval-${Math.random()}`); Object.assign(f.doc.segments[0], over); reseal(f.doc); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => /SEGMENT_(INTERVAL|DURATION)_INVALID/.test(e.code))); } });
test('T3-6 duplicate segment and two active sources for one section fail', () => { const f = complete('duplicate'); const extra = segment(f.master, 1, { segment_id: 'segment-other', in_s: 8, out_s: 10, duration_s: 2 }); f.doc = authority.registerSegment(f.doc, extra); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'SECTION_ACTIVE_SOURCE_AMBIGUOUS')); });
test('T3-7 provisional machine boundary remains registered but cannot become assembly eligible', () => { const f = complete('provisional'); f.doc.segments[0].boundary.class = 'MACHINE_INFERRED_PROVISIONAL'; reseal(f.doc); const handoff = authority.buildEditorHandoff(f.doc, options(f)); assert.equal(handoff.ready, false); assert.ok(handoff.blockers.some((e) => e.code === 'SEGMENT_BOUNDARY_PROVISIONAL')); });
test('T3-8 missing section or selection blocks complete coverage', () => { const f = complete('coverage'); f.doc.segments.pop(); f.doc.human_selections.pop(); reseal(f.doc); const result = authority.validateAuthority(f.doc, options(f)); assert.ok(result.errors.some((e) => e.code === 'SECTION_SEGMENT_MISSING')); });
test('T3-9 KEEP ALL binds the exact complete master set', () => { const f = complete('review'); f.doc.human_reviews[0].masters = []; f.doc.human_reviews[0].review_binding_sha256 = authority.reviewDigest(f.doc.human_reviews[0]); reseal(f.doc); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'REVIEW_MASTER_BINDING_STALE_OR_PARTIAL')); });
test('T3-10 tampered review and forged agent reviewer fail', () => { const f = complete('tampered'); f.doc.human_reviews[0].verdict = 'PARTIAL_KEEP'; reseal(f.doc); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'REVIEW_BINDING_INVALID')); const g = complete('forged'); g.doc.human_reviews[0].reviewer = { type: 'HUMAN', id: 'hermes' }; g.doc.human_reviews[0].review_binding_sha256 = authority.reviewDigest(g.doc.human_reviews[0]); reseal(g.doc); assert.ok(authority.validateAuthority(g.doc, options(g)).errors.some((e) => e.code === 'REVIEWER_AUTHORITY_INVALID')); });
test('T3-11 changed selection becomes stale; successor selection preserves history', () => { const f = complete('selection'); f.doc.human_selections[0].media_sha256 = H('wrong'); f.doc.human_selections[0].selection_binding_sha256 = authority.selectionDigest(f.doc.human_selections[0]); reseal(f.doc); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'SELECTION_LINEAGE_INVALID')); const g = complete('successor'); g.doc = authority.selectSegment(g.doc, { selection_id: 'selection-new', review_id: 'review-1', segment_id: 'segment-1', master_id: g.master.master_id, media_sha256: g.master.media.sha256, section_id: 'section-1', selector: { type: 'HUMAN', id: 'MIKKO' }, selected_at: NOW, status: 'ACTIVE' }); assert.equal(g.doc.human_selections.find((s) => s.selection_id === 'selection-1').status, 'SUPERSEDED'); });
test('T3-12 proxy, Piper, Draft V1, renamed, copied known proxy bytes all fail', () => { for (const marker of ['proxy-master', 'piper-master', 'draft-v1-master', 'synthetic-master']) { const f = complete(marker); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'MASTER_PROXY_SYNTHETIC_FORBIDDEN')); } const f = complete('copied-bytes'); const result = authority.validateAuthority(f.doc, { ...options(f), knownNonHumanMediaHashes: [f.master.media.sha256] }); assert.ok(result.errors.some((e) => e.code === 'MASTER_KNOWN_PROXY_BYTES_FORBIDDEN')); });
test('T3-13 human-labelled sidecar cannot redeem known proxy bytes', () => { const f = complete('sidecar-attack'); const result = authority.validateAuthority(f.doc, { ...options(f), knownNonHumanMediaHashes: [f.master.media.sha256] }); assert.equal(result.ok, false); });
test('T3-13b absent proxy/synthetic hash registry fails closed', () => { const f = complete('registry-missing'); const opts = options(f); delete opts.knownNonHumanMediaHashes; assert.ok(authority.validateAuthority(f.doc, opts).errors.some((e) => e.code === 'NON_HUMAN_MEDIA_REGISTRY_REQUIRED')); });
test('T3-14 sidecar mutation, wrong identity, and missing sidecar fail', () => { const f = complete('sidecar-mutation'); fs.appendFileSync(f.master.sidecar.path, 'x'); assert.ok(authority.validateAuthority(f.doc, options(f)).errors.some((e) => e.code === 'MASTER_SIDECAR_MUTATED')); const g = complete('sidecar-wrong'); const bad = { ...g.sidecar, run_id: 'wrong' }; fs.writeFileSync(g.master.sidecar.path, JSON.stringify(bad)); g.doc.masters[0].sidecar.sha256 = H(JSON.stringify(bad)); reseal(g.doc); assert.ok(authority.validateAuthority(g.doc, options(g)).errors.some((e) => e.code === 'MASTER_SIDECAR_LINEAGE_INVALID')); });
test('T3-15 Editor handoff names exact selected source, hash, interval, Story, plan, unit and capture provenance', () => { const f = complete('handoff'); const out = authority.buildEditorHandoff(f.doc, options(f)); assert.equal(out.ready, true); assert.deepEqual(Object.keys(out.sources[0]).sort(), ['capture_provenance','derivative_is_authority','duration_s','framing_setup','in_s','master_id','master_media_path','master_media_sha256','out_s','quality_class','recording_unit_id','section_id','selected_segment_id','story','visual_plan'].sort()); assert.equal(out.sources[0].derivative_is_authority, false); });

test('T3-CAP1 annotation is metadata and cannot alter delivery-script identity', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cap1-')); fs.writeFileSync(path.join(dir, 'final-script.md'), 'script'); const binding = { provenance: { source_artifact: 'final-script.md', source_artifact_annotation: 'First Real Run canonical delivery copy', source_artifact_sha256: H('script') } }; const resolved = readiness.resolveDeliveryScript(binding, dir); assert.equal(resolved.ok, true); assert.equal(resolved.file, path.join(dir, 'final-script.md')); assert.equal(resolved.annotation, 'First Real Run canonical delivery copy'); });
test('T3-CAP1 old annotated-path shape fails closed instead of guessing', () => { const result = readiness.resolveDeliveryScript({ provenance: { source_artifact: 'final-script.md (canonical)' } }, '/tmp/run'); assert.equal(result.ok, false); assert.equal(result.code, 'DELIVERY_SCRIPT_ARTIFACT_ID_INVALID'); });
test('T3-CAP2 PRESTO profile is bounded real-human declarative configuration', () => { const profile = capture.profileFor('presto-webcam-1080p30-mic'); assert.equal(profile.origin, 'HUMAN'); assert.equal(profile.captureClass, 'REAL_HUMAN_PERFORMANCE'); assert.equal(profile.qualityClass, 'PROOF_CAPTURE'); assert.equal(profile.cadenceAcceptance, 'MEASURED_NOT_NOMINAL'); assert.equal(profile.audioSampleRate, 48000); const valid = capture.validateProductionCaptureDeclaration(profile.profile, { host: 'presto', videoDevice: '@device_cm_video', audioDevice: '@device_cm_audio', destination: '/run/captures', allowedDestination: '/run' }); assert.equal(valid.ok, true, valid.errors.join('; ')); assert.throws(() => capture.buildFfmpegCommand({ profile: profile.profile, outputFile: '/tmp/x.mp4' }), /requires.*controller/); });
test('T3-CAP2 wrong host, missing devices and outside destination fail', () => { const result = capture.validateProductionCaptureDeclaration('presto-webcam-1080p30-mic', { host: 'vidnux', destination: '/other', allowedDestination: '/run' }); assert.equal(result.ok, false); assert.match(result.errors.join(' '), /host|video device|audio device|outside/); });
test('T3-CAP2 human sidecar binds exact run, bytes, Story, plan and device identities', () => { const sidecar = capture.buildHumanCaptureSidecar({ profile: 'presto-webcam-1080p30-mic', host: 'presto', videoDevice: '@device_cm_video', audioDevice: '@device_cm_audio', destination: '/run/captures', allowedDestination: '/run', runId: 'run-1', masterId: 'master-1', mediaSha256: H('media'), story: STORY, visualPlan: PLAN, capturedAt: NOW }); assert.equal(sidecar.origin, 'HUMAN'); assert.equal(sidecar.quality_class, 'PROOF_CAPTURE'); assert.equal(sidecar.media_sha256, H('media')); assert.equal(sidecar.device_provenance.video.identity, '@device_cm_video'); });
test('T3-CAP3 stable ID then alternative ID then unique friendly name precedence', () => { const devices = [{ kind: 'video', stable_id: 'stable-v', alternative_id: '@device_cm_v', friendly_name: 'C920 (Camera): A&B' }, { kind: 'audio', stable_id: 'stable-a', alternative_id: '@device_cm_a', friendly_name: 'Wave:3 — Ääni' }]; assert.equal(dshow.resolveDirectShowDevice(devices, { kind: 'video', stable_id: 'stable-v', friendly_name: 'wrong' }).resolved_by, 'stable_id'); assert.equal(dshow.resolveDirectShowDevice(devices, { kind: 'video', alternative_id: '@device_cm_v' }).resolved_by, 'alternative_id'); assert.equal(dshow.resolveDirectShowDevice(devices, { kind: 'audio', friendly_name: 'Wave:3 — Ääni' }).resolved_by, 'friendly_name'); });
test('T3-CAP3 duplicate names, missing choices and camera/mic cross-selection fail closed', () => { const duplicates = [{ kind: 'video', friendly_name: 'Camera' }, { kind: 'video', friendly_name: 'Camera' }, { kind: 'audio', friendly_name: 'Mic' }]; assert.throws(() => dshow.resolveDirectShowDevice(duplicates, { kind: 'video', friendly_name: 'Camera' }), (e) => e.code === 'DSHOW_DEVICE_AMBIGUOUS'); assert.throws(() => dshow.resolveDirectShowDevice(duplicates, { kind: 'video' }), (e) => e.code === 'DSHOW_DEVICE_CHOICE_REQUIRED'); assert.throws(() => dshow.resolveDirectShowDevice(duplicates, { kind: 'video', friendly_name: 'Mic' }), (e) => e.code === 'DSHOW_DEVICE_KIND_MISMATCH'); });

test('T3-A gate policy keeps Production assembly planned and forbids Draft assembler substitution', () => { const policy = require('../config/gate-mode-policy.json'); const production = policy.gates['rough-cut-review'].modes.PRODUCTION; assert.equal(production.implementation_status, 'PLANNED'); assert.match(production.meaning, /Nothing in the DRAFT assembler may stand in for it/); });
