'use strict';
const { assert, test, tests } = require('./_helpers.js');
const vp = require('../scripts/visual-plan.js');
const director = require('../scripts/visual-planning-director.js');

const H = vp.sha256('story');
const B1 = 'visual-beat-01HF7YAT010000000000000001';
const B2 = 'visual-beat-01HF7YAT020000000000000002';
const routeSelector = () => ({ ok: true, decision: 'ROUTE', selected_host: 'TEST_LOCAL', endpoint: 'http://127.0.0.1:1', model: 'TEST_MODEL' });
const ids = (() => { let n = 10; return { shot: () => `shot-01HF7YAT${String(n++).padStart(2, '0')}0000000000000000`, prompt: () => `prompt-01HF7YBT${String(n++).padStart(2, '0')}0000000000000000`, plan: () => 'visual-plan-01HF7YCT000000000000000000' }; })();
function task(over = {}) { return { task_id: 'vp-task-1', action: 'plan_visuals', requested_by: 'hermes', project_id: 'project-1', story: { project_id: 'project-1', version_id: 'version-1', content_hash: H, approval: { state: 'approved', approved_by: 'TEST_HUMAN', approved_at: '2026-08-23T10:00:00Z', version_id: 'version-1', content_hash: H }, central_claim: 'Use proof-driven production choices.', narrative_spine: 'problem-solution-proof', sections: [{ section_id: 'hook', order: 1, dialogue: 'Speed is not the real bottleneck.' }, { section_id: 'proof', order: 2, dialogue: 'Ask whether the workflow preserves proof.' }] }, required_beats: [{ canonical_beat_id: B1, section_id: 'hook', aliases: [{ namespace: 'vidtoolz-beat-sheet/beat', id: 'b-11111111' }], source_provenance: { source_system: 'beat-sheet', source_id: 'b-11111111' }, edit_placement: 'hook', priority: 'HIGH' }, { canonical_beat_id: B2, section_id: 'proof', aliases: [], source_provenance: null, edit_placement: 'proof', priority: 'NORMAL' }], research: { bindings_doc: { bindings: [] }, current_result_refs: [], required_constraint_ids: [], authority_by_binding: {} }, output_target: { aspect_ratio: '9:16', orientation: 'vertical' }, privacy: { local_only: true }, retry_budget: 2, cost_budget: { max_model_calls: 2 }, ...over }; }
function shot(over = {}) { return { visual_purpose: 'make the abstract choice concrete', narrative_function: 'illustrate the decision', media_type: 'GENERATED_STILL', generation_mode: 'STILL', subject: 'creator comparing two production paths', shot_brief: 'Vertical editorial workstation comparison with clean negative space.', why_it_serves_story: 'Makes the choice legible without changing the thesis.', presenter_relation: 'BROLL_OVERLAY', duration_target_s: 4, research_sensitive: false, research_binding_ids: [], required_constraint_ids: [], visual_assertion: null, camera_required: false, camera_intent: null, continuity_notes: ['same workstation'], alternatives: ['presenter only'], priority: 'HIGH', input_artifact_refs: [], quality_constraints: ['no readable generated UI text'], candidate_count_request: 2, ...over }; }
function semantic(over = {}) { return { beats: [{ canonical_beat_id: B1, coverage_decision: 'PLAN_SHOTS', no_visual_reason: null, shots: [shot()] }, { canonical_beat_id: B2, coverage_decision: 'INTENTIONAL_NO_VISUAL', no_visual_reason: 'Presenter delivers the proof directly.', shots: [] }], coverage_findings: [], continuity_findings: [], redundancy_findings: [], human_attention: [], recommendation: 'PLAN_READY', ...over }; }
const opts = (sem = semantic(), extra = {}) => ({ routeSelector, modelAdapter: async () => JSON.stringify(sem), newShotId: ids.shot, newPromptId: ids.prompt, newPlanId: ids.plan, now: '2026-08-23T11:00:00Z', ...extra });

test('VP1 registration identity', () => assert.equal(director.AGENT_ID, 'visual_planning_director'));
test('VP2 owns shot planning', () => assert.ok(director.ACTIONS.includes('plan_visuals')));
test('VP3 no Creative authority', () => assert.ok(!director.ACTIONS.includes('set_creative_identity')));
test('VP4 no Camera mechanics', () => assert.ok(!vp.CAMERA_INTENT_FIELDS.includes('heading')));
test('VP5 no generation routing', () => assert.equal(director.generationSupervisorProjection(task(), { prompts: [] }, { shot_id: 's', beat_ref: { canonical_beat_id: B1 }, narrative_function: 'x', generation_requirements: { artifact_class: 'image', quality_constraints: [], input_artifact_refs: [] }, prompt_refs: [] }).routing, undefined));
test('VP6 no final selection action', () => assert.ok(!director.ACTIONS.includes('select_asset')));
test('VP7 exact Story accepted', () => assert.equal(director.preflight(task()).ok, true));
test('VP8 wrong hash blocks before model', async () => { let calls = 0; const t = task(); t.story.content_hash = 'bad'; const out = await director.run(t, { modelAdapter: async()=>{calls++;} }); assert.equal(out.state, 'BLOCKED'); assert.equal(calls, 0); });
test('VP9 approved Story creates production-intent review plan', async () => assert.equal((await director.run(task(), opts())).state, 'AWAITING_HUMAN_REVIEW'));
test('VP10 candidate Story is preview only', async () => { const t=task(); t.story.approval={state:'none',approved_by:null,approved_at:null,version_id:'version-1',content_hash:H}; assert.equal((await director.run(t,opts())).state,'PREVIEW_ONLY'); });
test('VP11 unknown section blocks', () => { const t=task(); t.required_beats[0].section_id='missing'; assert.equal(director.preflight(t).ok,false); });
test('VP12 Story drift aborts write', async () => { const out=await director.run(task(),opts(semantic(),{reloadStory:async()=>({...task().story,content_hash:vp.sha256('drift')})})); assert.equal(out.reason,'SOURCE_STORY_CHANGED'); assert.equal(out.visual_plan,null); });
test('VP13 stale Research blocks', async () => researchState('STALE',false,'RETURN_TO_RESEARCH'));
test('VP14 invalid Research blocks', async () => researchState('INVALID',false,'RETURN_TO_RESEARCH'));
test('VP15 RESEARCH_MORE returns Research', async () => researchState('VALID',false,'RETURN_TO_RESEARCH','RESEARCH_MORE'));
test('VP16 constraint preservation', async () => { const {out}=await researchRun(); assert.deepEqual(out.visual_plan.shots[0].research_refs[0].applied_constraint_ids,['constraint-1']); });
test('VP17 misleading visual protection', () => { const bad=semantic(); bad.beats[0].shots[0].research_sensitive=true; bad.beats[0].shots[0].visual_assertion='CLOUD = SLOW'; bad.beats[0].shots[0].research_binding_ids=[]; assert.equal(director.validateSemanticOutput(bad,task()).ok,false); });
test('VP18 every beat exactly once', () => assert.equal(director.validateSemanticOutput(semantic(),task()).ok,true));
test('VP19 missing beat rejected', () => { const s=semantic(); s.beats.pop(); assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP20 unknown beat rejected', () => { const s=semantic(); s.beats[0].canonical_beat_id='visual-beat-01HF7YAT990000000000000099'; assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP21 duplicate beat rejected', () => { const s=semantic(); s.beats[1]=structuredClone(s.beats[0]); assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP22 intentional-none accepted', () => assert.equal(director.validateSemanticOutput(semantic(),task()).ok,true));
test('VP23 empty no-visual rationale rejected', () => { const s=semantic(); s.beats[1].no_visual_reason=''; assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP24 media enum enforced', () => { const s=semantic(); s.beats[0].shots[0].media_type='MAGIC'; assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP25 brief and rationale required', () => { const s=semantic(); s.beats[0].shots[0].why_it_serves_story=''; assert.equal(director.validateSemanticOutput(s,task()).ok,false); });
test('VP26 model IDs rejected', () => { const s=semantic(); s.beats[0].shots[0].shot_id='x'; assert.equal(director.validateSemanticOutput(s,task()).ok,false); });

async function researchRun(state='VALID',authorization=true,recommendation='ALLOW_USE_WITH_QUALIFICATION') { const t=task(); const binding={binding_id:'bind-1',claim_ref:{namespace:'vidtoolz-episode-factory/package-run-claim',canonical_id:'claim-00000000-0000-4000-8000-000000000001',revision:1},assertion_text_sha256:vp.sha256('claim')}; const rr={binding_id:'bind-1',result_id:'research-result-00000000-0000-4000-8000-000000000001',result_revision:1,result_digest_sha256:vp.sha256('rr'),human_exception_ref:null}; t.research={bindings_doc:{bindings:[binding]},current_result_refs:[rr],required_constraint_ids:['constraint-1'],authority_by_binding:{'bind-1':{...rr,claim_ref:binding.claim_ref,assertion_sha256:binding.assertion_text_sha256,result_state:state,recommendation,authorization_ok:authorization,required_constraint_ids:['constraint-1']}}}; const s=semantic(); Object.assign(s.beats[0].shots[0],{research_sensitive:true,research_binding_ids:['bind-1'],required_constraint_ids:['constraint-1'],visual_assertion:'Cloud editing can introduce latency under high-resolution workloads.'}); return {out:await director.run(t,opts(s)),t,s}; }
async function researchState(state,auth,expected,recommendation) { const {out}=await researchRun(state,auth,recommendation); assert.equal(out.state,expected); }
test('VP27 deterministic writer owns shot IDs', async()=>assert.match((await director.run(task(),opts())).visual_plan.shots[0].shot_id,/^shot-/));
test('VP28 canonical plan created', async()=>assert.equal((await director.run(task(),opts())).visual_plan.artifact_type,'visual-plan'));
test('VP29 plan digest valid', async()=>assert.equal((await director.run(task(),opts())).validation.ok,true));
test('VP30 plan revision one', async()=>assert.equal((await director.run(task(),opts())).visual_plan.plan_revision,1));
test('VP31 prompt exact shot binding', async()=>{const p=(await director.run(task(),opts())).visual_plan;assert.equal(p.prompts[0].shot_id,p.shots[0].shot_id);});
test('VP32 shot-intent digest exact', async()=>{const p=(await director.run(task(),opts())).visual_plan;assert.equal(p.prompts[0].shot_intent_digest_sha256,vp.shotIntentDigest(p.shots[0]));});
test('VP33 changed intent invalidates prompt', async()=>{const p=(await director.run(task(),opts())).visual_plan;p.shots[0].subject='changed';p.plan_digest_sha256=vp.planDigest(p);assert.equal(vp.validatePlan(p).prompts_current,false);});
test('VP34 Camera intent accepted',()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{camera_required:true,camera_intent:{subject:'Helsinki',purpose:'establish geography',desired_reveal:'Tallinn relationship',movement_need:'moving',geographic_context:'Helsinki-Tallinn'}});assert.equal(director.validateSemanticOutput(s,task()).ok,true);});
test('VP35 Camera mechanics rejected',()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{camera_required:true,camera_intent:{heading:'90'}});assert.equal(director.validateSemanticOutput(s,task()).ok,false);});
test('VP36 map handoff intent only',async()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{media_type:'MAP_ANIMATION',generation_mode:'NOT_APPLICABLE',camera_required:true,camera_intent:{subject:'Helsinki-Tallinn',purpose:'show proximity',desired_reveal:'route scale',movement_need:'moving',geographic_context:'Baltic'}});const out=await director.run(task(),opts(s));assert.ok(out.camera_handoffs[0].camera_intent);assert.equal(out.camera_handoffs[0].heading,undefined);});
test('VP37 neutral generation requirements',async()=>assert.equal((await director.run(task(),opts())).visual_plan.shots[0].generation_requirements.artifact_class,'generated_still'));
test('VP38 handoff route fields absent',async()=>assert.equal((await director.run(task(),opts())).generation_handoffs[0].routing,undefined));
test('VP39 candidate count bounded',async()=>{const s=semantic();s.beats[0].shots[0].candidate_count_request=99;assert.equal((await director.run(task(),opts(s))).visual_plan.shots[0].generation_requirements.candidate_count_request,4);});
test('VP40 I2V requires input image',()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{media_type:'GENERATED_VIDEO',generation_mode:'IMAGE_TO_VIDEO',input_artifact_refs:[]});assert.equal(director.validateSemanticOutput(s,task()).ok,false);});
test('VP41 presenter enum',()=>{const s=semantic();s.beats[0].shots[0].presenter_relation='DIRECTOR';assert.equal(director.validateSemanticOutput(s,task()).ok,false);});
test('VP42 Presenter authority separate',()=>{const s=semantic();s.beats[0].shots[0].selected_take='take-1';assert.equal(director.validateSemanticOutput(s,task()).ok,false);});
test('VP43 continuity survives writing',async()=>assert.deepEqual((await director.run(task(),opts())).visual_plan.shots[0].continuity_notes,['same workstation']));
test('VP44 redundancy advisory only',async()=>{const s=semantic({redundancy_findings:['workstation repeats']});const out=await director.run(task(),opts(s));assert.equal(out.state,'AWAITING_HUMAN_REVIEW');assert.deepEqual(out.semantic.redundancy_findings,['workstation repeats']);});
test('VP45 no plan self-approval',async()=>assert.equal((await director.run(task(),opts())).visual_plan.approval,undefined));
test('VP46 no READY without human approval',async()=>assert.equal((await director.run(task(),opts())).authority.authorization_ok,false));
test('VP47 no final asset approval',async()=>assert.equal((await director.run(task(),opts())).visual_plan.shots[0].selected_asset_id,undefined));
test('VP48 malformed output retries',async()=>{let n=0;const out=await director.run(task(),opts(semantic(),{modelAdapter:async()=>++n===1?'bad':JSON.stringify(semantic())}));assert.equal(out.attempts,2);});
test('VP49 retry exhaustion escalates',async()=>assert.equal((await director.run(task(),opts(semantic(),{modelAdapter:async()=>'bad'}))).state,'ESCALATED'));
test('VP50 frontier recommendation does not dispatch',async()=>{let calls=0;const out=await director.run(task({risk_level:'FRONTIER_RECOMMENDED',privacy:{local_only:false}}),{modelAdapter:async()=>{calls++;}});assert.equal(out.state,'ESCALATED');assert.equal(calls,0);});
test('VP51 privacy local_only enforced',async()=>assert.equal((await director.run(task({risk_level:'FRONTIER_RECOMMENDED'}),{})).state,'BLOCKED'));
test('VP52 CANARY A repository-grounded straightforward plan',async()=>{const fixture=require('./fixtures/visual-planning-director/stop-chasing-ai-speed.json');const content_hash=vp.sha256(JSON.stringify(fixture.sections));const story={project_id:fixture.project_id,version_id:'unit-b-approved-v1',content_hash,approval:{state:'approved',approved_by:'TEST_HUMAN',approved_at:'2026-08-23T10:00:00Z',version_id:'unit-b-approved-v1',content_hash},central_claim:fixture.central_claim,narrative_spine:fixture.narrative_spine,sections:fixture.sections};const beats=task().required_beats.map((b,i)=>({...b,section_id:fixture.sections[i].section_id}));const out=await director.run(task({project_id:fixture.project_id,story,required_beats:beats}),opts());assert.equal(out.validation.coverage_complete,true);assert.equal(out.state,'AWAITING_HUMAN_REVIEW');assert.equal(fixture.source_repository,'vidtoolz-media-pipeline');});
test('VP53 CANARY B grounded claim-19.23 cannot bypass RESEARCH_MORE',async()=>{const grounded=require('./fixtures/research-result/claim-19.23.json').results[0];assert.equal(grounded.sources.length,2);assert.equal(grounded.evidence.length,4);const t=task();const binding={binding_id:'bind-1',claim_ref:grounded.claim_ref,assertion_text_sha256:vp.sha256('Cloud editing can introduce latency under high-resolution workloads.')};const current={binding_id:'bind-1',result_id:grounded.result_id,result_revision:grounded.result_revision,result_digest_sha256:grounded.result_digest_sha256,human_exception_ref:null};t.research={bindings_doc:{bindings:[binding]},current_result_refs:[current],required_constraint_ids:grounded.qualification.wording_constraints.map(c=>c.constraint_id),authority_by_binding:{'bind-1':{...current,claim_ref:grounded.claim_ref,assertion_sha256:binding.assertion_text_sha256,result_state:'VALID',recommendation:'RESEARCH_MORE',authorization_ok:false,required_constraint_ids:grounded.qualification.wording_constraints.map(c=>c.constraint_id)}}};const s=semantic();Object.assign(s.beats[0].shots[0],{research_sensitive:true,research_binding_ids:['bind-1'],required_constraint_ids:t.research.required_constraint_ids,visual_assertion:'Cloud editing can introduce latency under high-resolution workloads.'});const out=await director.run(t,opts(s));assert.equal(out.state,'RETURN_TO_RESEARCH');assert.equal(out.authority.authorization_ok,false);});
test('VP54 CANARY C map intent has no mechanics',async()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{media_type:'MAP_ANIMATION',generation_mode:'NOT_APPLICABLE',camera_required:true,camera_intent:{subject:'Helsinki-Tallinn',purpose:'geography',desired_reveal:'distance',movement_need:'moving',geographic_context:'Baltic'}});const out=await director.run(task(),opts(s));assert.equal(JSON.stringify(out.camera_handoffs).includes('heading'),false);});
test('VP55 CANARY D video handoff neutral',async()=>{const s=semantic();Object.assign(s.beats[0].shots[0],{media_type:'GENERATED_VIDEO',generation_mode:'DIRECT_VIDEO'});const out=await director.run(task(),opts(s));assert.equal(out.generation_handoffs[0].brief.input_artifacts.length,0);assert.equal(out.generation_handoffs[0].host,undefined);});
test('VP56 CANARY E missing coverage blocks',async()=>{const s=semantic();s.beats.pop();assert.equal((await director.run(task(),opts(s))).state,'ESCALATED');});
test('VP57 CANARY F presenter balance legal',async()=>{const s=semantic();s.beats[0].shots[0].media_type='PRESENTER_A_ROLL';s.beats[0].shots[0].generation_mode='NOT_APPLICABLE';s.beats[0].shots[0].presenter_relation='PRESENT';const out=await director.run(task(),opts(s));assert.equal(out.visual_plan.shots[0].presenter_relation,'PRESENT');});
test('VP58 prompt adapter uses existing builder',async()=>assert.equal((await director.run(task(),opts())).visual_plan.prompts[0].origin,'super-focus-builder'));
test('VP59 Visual Plan validator invoked',async()=>assert.ok((await director.run(task(),opts())).validation));
test('VP60 evaluatePlanAuthority invoked',async()=>assert.ok((await director.run(task(),opts())).authority));
test('VP61 Generation projection no route',async()=>assert.equal((await director.run(task(),opts())).generation_handoffs[0].lane,undefined));
test('VP62 Camera projection no mechanics',()=>{const shot={shot_id:'s',beat_ref:{canonical_beat_id:B1},camera_intent:{subject:'x',purpose:'y'}};assert.equal(director.cameraProjection({plan_id:'p'},shot).camera_intent.heading,undefined);});
test('VP63 standalone harness marker',()=>assert.ok(require('fs').readFileSync(__filename,'utf8').includes('Visual Planning Director tests passed')));
test('VP64 canonical runner registers exactly once',()=>assert.equal(require('fs').readFileSync(require('path').join(__dirname,'run-tests.js'),'utf8').split('visual-planning-director.test.js').length-1,1));

if(require.main===module)(async()=>{let passed=0,failed=0;for(const item of tests){try{await item.fn();passed++;console.log(`ok ${passed} - ${item.name}`)}catch(error){failed++;console.error(`not ok - ${item.name}`);console.error(error.stack||error.message)}}console.log(`${passed}/${passed+failed} Visual Planning Director tests passed`);if(failed)process.exitCode=1})();
module.exports={tests};
