presto_legacy_comfyui:
  base_path: C:/Users/presto/Documents/ComfyUI
  checkpoints: models/checkpoints
  clip: models/clip
  clip_vision: models/clip_vision
  configs: models/configs
  controlnet: models/controlnet
  diffusers: models/diffusers
  diffusion_models: |
    models/diffusion_models
    models/unet
  embeddings: models/embeddings
  gligen: models/gligen
  hypernetworks: models/hypernetworks
  loras: models/loras
  photomaker: models/photomaker
  style_models: models/style_models
  text_encoders: |
    models/text_encoders
    models/clip
  unet: models/unet
  upscale_models: models/upscale_models
  vae: models/vae
  vae_approx: models/vae_approx
  animatediff_models: models/animatediff_models
  animatediff_motion_lora: models/animatediff_motion_lora
  animatediff_video_formats: models/animatediff_video_formats
  CogVideo: models/CogVideo
  cogvideo: models/CogVideo
  liveportrait: models/liveportrait
