#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")/.."

node tests/run-tests.js
node --check episode-model.js
node --check storage-adapter.js
node --check app.js
node --check package-engine-model.js
node --check package-engine-run.js
node --check package-engine.js
node --check workflow-path.js
node --check script-commitment-check.js
node --check resolve-handoff-readiness.js
node --check media-routing.js
node --check media-provenance.js
node --check package-media-index.js
node --check manual-media-import.js
node --check project-state-resolver.js
node --check next-task-engine.js
node --check project-action-registry.js
node --check project-discovery.js
node --check project-client.js
node --check idea-promotion.js
node --check topic-idea-scout.js
node --check project-script.js
node --check project-image-prompts.js
node --check score-explanation.js
node --check scripts/import-manual-images.js
node --check scripts/import-manual-videos.js
node --check scripts/index-package-media.js
node --check scripts/backfill-score-explanation.js
node --check package-engine-server.js
node --check package-runs-dashboard.js
node --check trailer-cue-generator.js
node --check music-cue-generator.js
node --check supervised-capture.js
node --check earth-studio-job-planner.js
node --check scripts/episode-factory.js
node --check scripts/resolve-handoff.js
node --check scripts/package-engine-new-run.js
node --check scripts/package-engine-new-outline.js
node --check scripts/package-engine-new-script.js
node --check scripts/package-engine-new-production.js
node --check scripts/package-run-research-pack.js
node --check scripts/package-run-research-evidence.js
node --check scripts/package-run-script-structure.js
node --check scripts/package-run-script-review.js
node --check scripts/package-run-production-plan.js
node --check scripts/package-run-shot-edit-plan-review.js
node --check scripts/package-run-capture-checklist.js
node --check scripts/package-run-capture-evidence-review.js
node --check scripts/package-run-capture-gap.js
node --check scripts/package-run-evidence-lint.js
node --check scripts/package-run-artifact-hygiene.js
node --check scripts/package-run-rough-cut-review.js
node --check scripts/package-run-final-review.js
node --check scripts/package-run-export-checklist.js
node --check scripts/package-run-publication-metadata.js
node --check scripts/package-run-newsletter.js
node --check scripts/package-run-archive-manifest.js
node --check scripts/package-run-repurpose.js
node --check scripts/package-run-broll-prompts.js
node --check scripts/package-run-creator-qa.js
node --check scripts/package-run-doctor.js
node --check scripts/package-run-next-action.js
node --check scripts/package-run-next-safe-action.js
node --check scripts/package-run-next-action-authority.js
node --check scripts/package-run-workflow-map.js
node --check scripts/package-run-active-state-audit.js
node --check scripts/package-run-state-proposal.js
node --check scripts/next-task-classifier.js
node --check scripts/package-run-production-approval-repair.js
node --check scripts/package-run-production-approval-review.js
node --check scripts/script-image-assets-dry-run.js
node --check scripts/script-image-assets-review-page.js
node --check scripts/topic-scout.js
node --check scripts/submitted-topics.js
node --check scripts/oneof10-input-helper.js
node --check scripts/daily-idea-scout.js
node --check scripts/daily-idea-scout-providers.js
node --check scripts/daily-idea-scout-launch.js
node --check scripts/daily-idea-scout-request.js
node --check scripts/package-runs-index.js
node --check scripts/system-registry.js
node --check scripts/generate-production-spec.js
node --check scripts/package-runs-dashboard-launch.js
node --check scripts/validate-published-videos.js
sh -n scripts/open-package-runs-dashboard.sh
sh -n scripts/open-active-run.sh
node --check scripts/trailer-cue-new.js
node --check scripts/music-cue-new.js
node --check scripts/supervised-capture.js
node --check scripts/earth-studio-job-plan.js
node --check scripts/docs-authority-check.js

# Operator-clarity guards: canonical spec stays in sync with pipeline-tracker.js,
# and authoritative docs keep no hardcoded test counts / stale phrases.
node scripts/generate-production-spec.js --check
node scripts/docs-authority-check.js
